// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Core.Base
{

	/// Every stored entity inherits this. The three fields are infrastructure, not business:
	/// PolyPersist needs them on IEntity, so they are marked @system_field and the emitter keeps
	/// them out of the business surface.
	public partial interface IBaseEntity
	{
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
	}
}
