
// <auto-generated>
// This code was generated by d3i.interpreter
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

import * as OrderIF_v1 from "../../../types/Sales/OrderManagement/OrderIF_v1";
import { BFFRestClient } from "../../../api/BFFRestClient";
import { AxiosError } from 'axios';
import Decimal from "decimal.js";

const rest = BFFRestClient.getInstance()

export const OrderIF = {
	V1: {
		async getOrder(orderId: string): Promise<OrderIF_v1.OrderDTO> {
			try {
				const extraHeaders = rest.getRequestHeaders("Sales.OrderManagement.getOrder");

				const response = await rest.axios.get<OrderIF_v1.OrderDTO>(
					`/sales/ordermanagement/orderif/v1/getorder/${encodeURIComponent(orderId)}`,
					{ headers: extraHeaders }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "getOrder");
			}
		}
		,
		async placeOrder(order: OrderIF_v1.OrderDTO): Promise<OrderIF_v1.OrderDTO> {
			try {
				const extraHeaders = rest.getRequestHeaders("Sales.OrderManagement.placeOrder");

				const response = await rest.axios.post<OrderIF_v1.OrderDTO>(
					`/sales/ordermanagement/orderif/v1/placeorder`,
					order,
					{ headers: { ...extraHeaders, 'Content-Type': 'application/json' } }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "placeOrder");
			}
		}
		,
		async setPrice(orderItem: OrderIF_v1.OrderItemDTO, price: Decimal): Promise<OrderIF_v1.OrderItemDTO> {
			try {
				const extraHeaders = rest.getRequestHeaders("Sales.OrderManagement.setPrice");

				const response = await rest.axios.post<OrderIF_v1.OrderItemDTO>(
					`/sales/ordermanagement/orderif/v1/setprice?price=${$price.toString()}`,
					orderItem,
					{ headers: { ...extraHeaders, 'Content-Type': 'application/json' } }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "setPrice");
			}
		}
		,
		async justOrder(orderId: string): Promise<{}> {
			try {
				const extraHeaders = rest.getRequestHeaders("Sales.OrderManagement.justOrder");

				const response = await rest.axios.post(
					`/sales/ordermanagement/orderif/v1/justorder/${encodeURIComponent(orderId)}`,
					{ headers: extraHeaders }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "justOrder");
			}
		}
		,
		}
}
