
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Sales.OrderManagement;
using Serilog.Context;
using ServiceKit.Net;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.Swagger;
using System.Net.Mime;

namespace Sales.OrderManagement
{
	[ApiController]
	[Route( "sales/ordermanagement/orderif/v2" )]
	public class OrderIF_v2_RestController : ControllerBase 
	{
		private readonly ILogger<OrderIF_v2_RestController> _logger;
		private readonly IOrderIF_v2 _service;
		public OrderIF_v2_RestController( ILogger<OrderIF_v2_RestController> logger, IOrderIF_v2 service )
		{
			_logger = logger; 
			_service = service; 
		}

		[HttpGet( "getorder/{orderId}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(IOrderIF_v2.OrderDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(ServiceKit.Net.Error) )]
		public async Task<IActionResult> getOrder( [FromRoute] string orderId)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.getOrder" ))
			{
				CallingContext ctx = CallingContext.PoolFromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.getOrder( ctx, orderId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(StatusCodes.Status501NotImplemented, "Not handled reponse in REST Controller when calling 'OrderIF_v2.getOrder'" );
						}
					}
					else
					{
						return StatusCode(response.Error.Status.ToHttp(), response.Error);
					}
				}
				catch(Exception ex)
				{
					return StatusCode(StatusCodes.Status500InternalServerError, new Error() { Status = Statuses.InternalError, MessageText = ex.Message, AdditionalInformation = ex.ToString()} );
				}
				finally
				{
					ctx.ReturnToPool();
				}
			}
		}

		[HttpPost( "placeorder" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(IOrderIF_v2.OrderDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(ServiceKit.Net.Error) )]
		public async Task<IActionResult> placeOrder( [FromBody] IOrderIF_v2.OrderDTO order)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.placeOrder" ))
			{
				CallingContext ctx = CallingContext.PoolFromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.placeOrder( ctx, order );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(StatusCodes.Status501NotImplemented, "Not handled reponse in REST Controller when calling 'OrderIF_v2.placeOrder'" );
						}
					}
					else
					{
						return StatusCode(response.Error.Status.ToHttp(), response.Error);
					}
				}
				catch(Exception ex)
				{
					return StatusCode(StatusCodes.Status500InternalServerError, new Error() { Status = Statuses.InternalError, MessageText = ex.Message, AdditionalInformation = ex.ToString()} );
				}
				finally
				{
					ctx.ReturnToPool();
				}
			}
		}

		[HttpPost( "justorder/{orderId}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "Ok" )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(ServiceKit.Net.Error) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(ServiceKit.Net.Error) )]
		public async Task<IActionResult> justOrder( [FromRoute] string orderId)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.justOrder" ))
			{
				CallingContext ctx = CallingContext.PoolFromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.justOrder( ctx, orderId );

					if( response.IsSuccess() == true )
					{
						return Ok();
					}
					else
					{
						return StatusCode(response.Error.Status.ToHttp(), response.Error);
					}
				}
				catch(Exception ex)
				{
					return StatusCode(StatusCodes.Status500InternalServerError, new Error() { Status = Statuses.InternalError, MessageText = ex.Message, AdditionalInformation = ex.ToString()} );
				}
				finally
				{
					ctx.ReturnToPool();
				}
			}
		}
	}
}
