
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Sales.OrderManagement.Protos;
using Serilog.Context;
using ServiceKit.Net;

namespace Sales.OrderManagement
{
	public class OrderIF_v1GrpcController : Sales.OrderManagement.Protos.OrderIF_v1.OrderIF_v1Base 
	{
		private readonly ILogger<OrderIF_v1GrpcController> _logger;
		private readonly IOrderIF_v1 _service;

		public OrderIF_v1GrpcController( ILogger<OrderIF_v1GrpcController> logger, IOrderIF_v1 service )
		{
			_logger = logger; 
			_service = service; 
		}

		public override async Task<OrderIF_v1_getOrderResponse> getOrder( OrderIF_v1_getOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.getOrder" ))
			{
				CallingContext ctx = CallingContext.PoolFromGrpcContext( grpcContext, _logger );
				try
				{
					var response = await _service.getOrder(ctx, request.OrderId);
					
					if( response.HasValue1() == true )
					{
						return new OrderIF_v1_getOrderResponse { Value1 = OrderDTO.ToGrpc( response.Value1 ) };
					}
					
					if( response.IsSuccess() == false )
					{
						return new OrderIF_v1_getOrderResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
					
					return new OrderIF_v1_getOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.NotImplemented,
							MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF.getOrder'",
						}
					};
					
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_getOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
				finally
				{
					ctx.ReturnToPool();
				}
			}
		}

		public override async Task<OrderIF_v1_placeOrderResponse> placeOrder( OrderIF_v1_placeOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.placeOrder" ))
			{
				CallingContext ctx = CallingContext.PoolFromGrpcContext( grpcContext, _logger );
				try
				{
					var response = await _service.placeOrder(ctx, request.Order);
					
					if( response.HasValue1() == true )
					{
						return new OrderIF_v1_placeOrderResponse { Value1 = response.Value1 };
					}
					
					if( response.IsSuccess() == false )
					{
						return new OrderIF_v1_placeOrderResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
					
					return new OrderIF_v1_placeOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.NotImplemented,
							MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF.placeOrder'",
						}
					};
					
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_placeOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
				finally
				{
					ctx.ReturnToPool();
				}
			}
		}
	}
}
