// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using ServiceKit.Net.Eventing;

namespace Sales.OrderManagement.Order
{
	/// The context's PRIVATE language. No version, and that is a statement: the consumers of
	/// this fact ship in the same deployment unit and move with it, so breaking its shape is
	/// a compile error rather than a wire incident.
	public partial class OrderPlaced : IEquatable<OrderPlaced>, IDomainEvent
	{
		/// <summary>How the platform recognises this shape. Generated; never hand-written.</summary>
		public string SchemaId => "Sales.OrderManagement.Order.OrderPlaced";

		/// <summary>The logical channel this fact travels on. Deployment maps it to a topic or queue.</summary>
		public string Channel => "Sales.OrderManagement";

		public string orderId { get; set; } = null!;
		public string customerId { get; set; } = null!;
		public decimal totalPrice { get; set; }

		#region Clone 
		public virtual OrderPlaced Clone()
		{
			OrderPlaced clone = new();

			clone.orderId = orderId;
			clone.customerId = customerId;
			clone.totalPrice = totalPrice;

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( OrderPlaced? other )
		{
			if (other is null) return false;

			if(orderId != other.orderId) return false;
			if(customerId != other.customerId) return false;
			if(totalPrice != other.totalPrice) return false;

			return true;
		}

		public override bool Equals(object? obj) => Equals(obj as OrderPlaced);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			hash.Add(orderId);
			hash.Add(customerId);
			hash.Add(totalPrice);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
