<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="PolyPersist.Net" />
    <PackageReference Include="PolyPersist.Net.Transactions" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="ServiceKit.Net.General" />
    <PackageReference Include="ServiceKit.Net.Service" />
    <PackageReference Include="ServiceKit.Net.Workflow" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Models\Sales.OrderManagement.Models.csproj" />
    <ProjectReference Include="..\Interfaces\Sales.OrderManagement.Interfaces.csproj" />
    <ProjectReference Include="..\..\Tracking\Models\Sales.Tracking.Models.csproj" />
  </ItemGroup>

</Project>
