
// <auto-generated>
// This code was generated by d3i.interpreter
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

import Decimal from "decimal.js";

export interface ValidationError {
	typeOfEntity: string;
	memberOfEntity: string;
	errorText: string;
}


export enum OrderStatuses {
	Draft = "Draft",
	Released = "Released",
	Finished = "Finished",
	Canceled = "Canceled",
}
export interface OrderItemDTO {
	productId:string;
	productName:string;
	quantity:Decimal;
	unitPrice:Decimal;
	subTotalPrice:Decimal;
	deliveryStatus:OrderItemDTO.DeliveryStatuses;
}

export namespace OrderItemDTO {

	export enum DeliveryStatuses {
		NotDelivered = "NotDelivered",
		PartiallyDelivered = "PartiallyDelivered",
		Delivered = "Delivered",
	}
}

export function validateOrderItemDTO( dto: OrderItemDTO ): ValidationError[] {
	const errors: ValidationError[] = [];
	if (dto.quantity <= 0)
		errors.push({ typeOfEntity: "OrderItemDTO", memberOfEntity: "quantity", errorText: "quantity must satisfy: value > 0" });
	if (dto.unitPrice < 0)
		errors.push({ typeOfEntity: "OrderItemDTO", memberOfEntity: "unitPrice", errorText: "unitPrice must satisfy: value >= 0" });
	return errors;
}
export interface OrderDTO {
	id:string;
	orderingDate:string;
	orderStatus:OrderStatuses;
	totalPrice:Decimal;
	customerData:OrderDTO.CustomerDataDTO;
	items:OrderItemDTO[];
	/// v2 addition: where the parcel is going
	shippingCity:string;
}

export namespace OrderDTO {
	export interface CustomerDataDTO {
		customerId:string;
		customerName:string;
	}

}
