
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

import Decimal from "decimal.js";


export enum OrderStatuses {
	Draft,
	Released,
	Finished,
	Canceled,
}
export interface OrderItemDTO {
	productId:string;
	productName:string;
	quantity:Decimal;
	UnitPrice:Decimal;
	subTotalPrice:string;
	deliveryStatus:OrderItemDTO.DeliveryStatuses;
}

export namespace OrderItemDTO {

	export enum DeliveryStatuses {
		NotDelivered,
		PartiallyDelivered,
		Delivered,
	}
}
export interface OrderDTO {
	orderingDate:string;
	orderStatus:OrderStatuses;
	totalPrice:Decimal;
	customerData:OrderDTO.CustomerDataDTO;
	items:OrderItemDTO[];
}

export namespace OrderDTO {
	export interface CustomerDataDTO {
		customerId:string;
		customerName:string;
	}

}
