
// <auto-generated>
// This code was generated by d3i.interpreter
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>



export enum CustomerStatuses {
	Pending = "Pending",
	Active = "Active",
	Suspended = "Suspended",
	Closed = "Closed",
}
export interface CustomerDTO {
	id:string;
	name:string;
	email:string;
	status:CustomerStatuses;
}

