// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using ServiceKit.Net.Eventing;

namespace Sales.OrderManagement
{
	/// <summary>
	/// Publishes 'OrderPlaced' as 'OrderIF' states it.
	///
	/// Generated and self-registering, so a translation cannot be declared and then quietly
	/// never run. WHAT it translates into is yours to write; THAT it runs is not.
	/// </summary>
	[AutoRegisterEventHandler]
	public sealed class OrderIF_v1OrderPlaced_v1Publisher : IEventHandler<Order.OrderPlaced>
	{
		private readonly IEventRecorder _recorder;

		public OrderIF_v1OrderPlaced_v1Publisher( IEventRecorder recorder ) => _recorder = recorder;

		public Task Handle( EventContext context, Order.OrderPlaced @event, CancellationToken cancellationToken = default )
		{
			// The same ordering scope as the fact it restates, so the outside world sees this
			// aggregate's contracts in the order the aggregate produced them.
			_recorder.Record( OrderIF_v1Translations.ToOrderPlaced_v1( @event ), context.PartitionKey );
			return Task.CompletedTask;
		}
	}

}
