// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using ServiceKit.Net;

namespace CustomerManagement.Customers
{
	public partial interface ICustomerService
	{
		/// <return>Customer.CustomerAccount</return>
		public Task<Response<Customer.CustomerAccount>> getCustomer(CallingContext ctx, string customerId);

		/// <return>Customer.CustomerAccount</return>
		public Task<Response<Customer.CustomerAccount>> registerCustomer(CallingContext ctx, string name, string email);


	}
}
