
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Google.Protobuf.Collections;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Globalization;

namespace Sales.OrderManagement
{
	public partial interface IOrderIF_v2
	{
		public Task<Response<OrderDTO>> getOrder(CallingContext ctx, string orderId);

		public Task<Response<OrderDTO>> placeOrder(CallingContext ctx, OrderDTO order);

		public Task<Response> justOrder(CallingContext ctx, string orderId);


		public partial class OrderPlaced_v1
		{
			public string orderId { get; set; }

			#region Clone & Copy 
			virtual public OrderPlaced_v1 Clone()
			{
				OrderPlaced_v1 clone = new();

				clone.orderId = new string(orderId.ToCharArray());

				return clone;
			}
			#endregion Clone & Copy 
		}

		public partial class OrderPlaced_v2
		{
			public string orderId { get; set; }

			#region Clone & Copy 
			virtual public OrderPlaced_v2 Clone()
			{
				OrderPlaced_v2 clone = new();

				clone.orderId = new string(orderId.ToCharArray());

				return clone;
			}
			#endregion Clone & Copy 
		}

		public enum OrderStatuses
		{
			Draft,
			Released,
			Finished,
			Canceled,
		}
		#region GrpcMapping
		public static class OrderStatusesMappings
		{
			public static Protos.OrderIF_v2.OrderStatuses ToGrpc( Sales.OrderManagement.IOrderIF_v2.OrderStatuses @this )
			{
				return @this switch
				{
					Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Draft => Protos.OrderIF_v2.OrderStatuses.Draft,
					Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Released => Protos.OrderIF_v2.OrderStatuses.Released,
					Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Finished => Protos.OrderIF_v2.OrderStatuses.Finished,
					Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Canceled => Protos.OrderIF_v2.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

			public static Sales.OrderManagement.IOrderIF_v2.OrderStatuses FromGrpc( Protos.OrderIF_v2.OrderStatuses @this )
			{
				return @this switch
				{
					Protos.OrderIF_v2.OrderStatuses.Draft => Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Draft,
					Protos.OrderIF_v2.OrderStatuses.Released => Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Released,
					Protos.OrderIF_v2.OrderStatuses.Finished => Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Finished,
					Protos.OrderIF_v2.OrderStatuses.Canceled => Sales.OrderManagement.IOrderIF_v2.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

		}
		#endregion GrpcMapping
		public partial class OrderItemDTO
		{
			public enum DeliveryStatuses
			{
				NotDelivered,
				PartiallyDelivered,
				Delivered,
			}
			#region GrpcMapping
			public static class DeliveryStatusesMappings
			{
				public static Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses ToGrpc( Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses @this )
				{
					return @this switch
					{
						Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.NotDelivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.NotDelivered,
						Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.PartiallyDelivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered,
						Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.Delivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

				public static Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses FromGrpc( Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses @this )
				{
					return @this switch
					{
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.NotDelivered => Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.NotDelivered,
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered => Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.PartiallyDelivered,
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.Delivered => Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

			}
			#endregion GrpcMapping
			public string productId { get; set; }
			public string productName { get; set; }
			public decimal quantity { get; set; }
			public decimal UnitPrice { get; set; }
			public string subTotalPrice { get; set; }
			public DeliveryStatuses deliveryStatus { get; set; }

			#region Clone & Copy 
			virtual public OrderItemDTO Clone()
			{
				OrderItemDTO clone = new();

				clone.productId = new string(productId.ToCharArray());
				clone.productName = new string(productName.ToCharArray());
				clone.quantity = quantity;
				clone.UnitPrice = UnitPrice;
				clone.subTotalPrice = new string(subTotalPrice.ToCharArray());
				clone.deliveryStatus = deliveryStatus;

				return clone;
			}
			#endregion Clone & Copy 

			#region GrpcMapping
			public static Protos.OrderIF_v2.OrderItemDTO ToGrpc( Sales.OrderManagement.IOrderIF_v2.OrderItemDTO @this )
			{
				Protos.OrderIF_v2.OrderItemDTO result = new();

				result.ProductId = @this.productId;
				result.ProductName = @this.productName;
				result.Quantity = @this.quantity.ToString(CultureInfo.InvariantCulture);
				result.UnitPrice = @this.UnitPrice.ToString(CultureInfo.InvariantCulture);
				result.SubTotalPrice = @this.subTotalPrice;
				result.DeliveryStatus = Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatusesMappings.ToGrpc( @this.deliveryStatus);

				return result;
			}
			public static Sales.OrderManagement.IOrderIF_v2.OrderItemDTO FromGrpc( Protos.OrderIF_v2.OrderItemDTO @from )
			{
				Sales.OrderManagement.IOrderIF_v2.OrderItemDTO result = new();

				result.productId = @from.ProductId;
				result.productName = @from.ProductName;
				result.quantity = decimal.Parse(@from.Quantity, CultureInfo.InvariantCulture);
				result.UnitPrice = decimal.Parse(@from.UnitPrice, CultureInfo.InvariantCulture);
				result.subTotalPrice = @from.SubTotalPrice;
				result.deliveryStatus = Sales.OrderManagement.IOrderIF_v2.OrderItemDTO.DeliveryStatusesMappings.FromGrpc( @from.DeliveryStatus);

				return result;
			}
			#endregion GrpcMapping
		}

		public partial class OrderDTO
		{
			public partial class CustomerDataDTO
			{
				public string customerId { get; set; }
				public string customerName { get; set; }

				#region Clone & Copy 
				virtual public CustomerDataDTO Clone()
				{
					CustomerDataDTO clone = new();

					clone.customerId = new string(customerId.ToCharArray());
					clone.customerName = new string(customerName.ToCharArray());

					return clone;
				}
				#endregion Clone & Copy 

				#region GrpcMapping
				public static Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO ToGrpc( Sales.OrderManagement.IOrderIF_v2.OrderDTO.CustomerDataDTO @this )
				{
					Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO result = new();

					result.CustomerId = @this.customerId;
					result.CustomerName = @this.customerName;

					return result;
				}
				public static Sales.OrderManagement.IOrderIF_v2.OrderDTO.CustomerDataDTO FromGrpc( Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO @from )
				{
					Sales.OrderManagement.IOrderIF_v2.OrderDTO.CustomerDataDTO result = new();

					result.customerId = @from.CustomerId;
					result.customerName = @from.CustomerName;

					return result;
				}
				#endregion GrpcMapping
			}

			public string orderingDate { get; set; }
			public OrderStatuses orderStatus { get; set; }
			public decimal totalPrice { get; set; }
			public CustomerDataDTO customerData { get; set; }
			public List<OrderItemDTO> items { get; set; } = new();

			#region Clone & Copy 
			virtual public OrderDTO Clone()
			{
				OrderDTO clone = new();

				clone.orderingDate = new string(orderingDate.ToCharArray());
				clone.orderStatus = orderStatus;
				clone.totalPrice = totalPrice;
				clone.customerData = customerData?.Clone();
				clone.items.AddRange( items.Select( v => v.Clone() ));

				return clone;
			}
			#endregion Clone & Copy 

			#region GrpcMapping
			public static Protos.OrderIF_v2.OrderDTO ToGrpc( Sales.OrderManagement.IOrderIF_v2.OrderDTO @this )
			{
				Protos.OrderIF_v2.OrderDTO result = new();

				result.OrderingDate = @this.orderingDate;
				result.OrderStatus = Sales.OrderManagement.IOrderIF_v2.OrderStatusesMappings.ToGrpc( @this.orderStatus);
				result.TotalPrice = @this.totalPrice.ToString(CultureInfo.InvariantCulture);
				result.CustomerData = @this.customerData != null ? Sales.OrderManagement.IOrderIF_v2.OrderDTO.CustomerDataDTO.ToGrpc( @this.customerData) : null;
				result.Items.AddRange( @this.items.Select( v => OrderItemDTO.ToGrpc( v ) ));

				return result;
			}
			public static Sales.OrderManagement.IOrderIF_v2.OrderDTO FromGrpc( Protos.OrderIF_v2.OrderDTO @from )
			{
				Sales.OrderManagement.IOrderIF_v2.OrderDTO result = new();

				result.orderingDate = @from.OrderingDate;
				result.orderStatus = Sales.OrderManagement.IOrderIF_v2.OrderStatusesMappings.FromGrpc( @from.OrderStatus);
				result.totalPrice = decimal.Parse(@from.TotalPrice, CultureInfo.InvariantCulture);
				result.customerData = @from.CustomerData != null ? Sales.OrderManagement.IOrderIF_v2.OrderDTO.CustomerDataDTO.FromGrpc( @from.CustomerData) : null;
				result.items.AddRange( @from.Items.Select( v => OrderItemDTO.FromGrpc(v) ));

				return result;
			}
			#endregion GrpcMapping
		}

	}
}
