
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement
{
	using ServiceKit.Net;

	public interface IOrderIF_v1
	{
		public class OrderItemDTO
		{
			public string productId { get; set; }
			public string productName { get; set; }
			public decimal quantity { get; set; }
			public string UnitPrice { get; set; }
			public string subTotalPrice { get; set; }
		}
		public class OrderDTO
		{
			public string customerId { get; set; }
			public string orderingDate { get; set; }
			public string totalPrice { get; set; }
			public List<OrderItemDTO> items { get; set; }
		}
		public Response<OrderDTO> getOrder(CallingContext ctx, string orderId);

		public Response<OrderDTO> placeOrder(CallingContext ctx, OrderDTO order);

	}
}
