
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement
{
	using ServiceKit.Net;

	public interface IOrderService
	{
		public Response<Order.OrderHeader> getOrder(CallingContext ctx, string orderId);

		public Response<Order.OrderHeader> placeOrder(CallingContext ctx, Order.OrderHeader order);

	}
}
