// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using ServiceKit.Net;

namespace CustomerManagement.Customers
{
	public partial interface ICustomerIF_v1
	{
		/// <return>ICustomerIF_v1.CustomerDTO</return>
		public Task<Response<ICustomerIF_v1.CustomerDTO>> getCustomer(CallingContext ctx, string customerId);

		/// <return>ICustomerIF_v1.CustomerDTO</return>
		public Task<Response<ICustomerIF_v1.CustomerDTO>> registerCustomer(CallingContext ctx, string name, string email);


		public enum CustomerStatuses
		{
			Pending,
			Active,
			Suspended,
			Closed,
		}
		#region GrpcMapping
		public static class CustomerStatusesMappings
		{
			public static Protos.CustomerIF_v1.CustomerStatuses ToGrpc( ICustomerIF_v1.CustomerStatuses @this )
			{
				return @this switch
				{
					ICustomerIF_v1.CustomerStatuses.Pending => Protos.CustomerIF_v1.CustomerStatuses.Pending,
					ICustomerIF_v1.CustomerStatuses.Active => Protos.CustomerIF_v1.CustomerStatuses.Active,
					ICustomerIF_v1.CustomerStatuses.Suspended => Protos.CustomerIF_v1.CustomerStatuses.Suspended,
					ICustomerIF_v1.CustomerStatuses.Closed => Protos.CustomerIF_v1.CustomerStatuses.Closed,
					_ => throw new NotImplementedException(), 
				};
			}

			public static ICustomerIF_v1.CustomerStatuses FromGrpc( Protos.CustomerIF_v1.CustomerStatuses @this )
			{
				return @this switch
				{
					Protos.CustomerIF_v1.CustomerStatuses.Pending => ICustomerIF_v1.CustomerStatuses.Pending,
					Protos.CustomerIF_v1.CustomerStatuses.Active => ICustomerIF_v1.CustomerStatuses.Active,
					Protos.CustomerIF_v1.CustomerStatuses.Suspended => ICustomerIF_v1.CustomerStatuses.Suspended,
					Protos.CustomerIF_v1.CustomerStatuses.Closed => ICustomerIF_v1.CustomerStatuses.Closed,
					_ => throw new NotImplementedException(), 
				};
			}

		}
		#endregion GrpcMapping
		public partial class CustomerDTO : IEquatable<CustomerDTO>
		{
			public string id { get; set; }
			public string name { get; set; }
			public string email { get; set; }
			public ICustomerIF_v1.CustomerStatuses status { get; set; }

			#region Clone 
			public virtual CustomerDTO Clone()
			{
				CustomerDTO clone = new();

				clone.name = new string(name.ToCharArray());
				clone.email = new string(email.ToCharArray());
				clone.status = status;

				return clone;
			}
			#endregion Clone 

			#region Equals & HashCode 
			public bool Equals( CustomerDTO other )
			{
				if (other is null) return false;

				if(name != other.name) return false;
				if(email != other.email) return false;
				if(status != other.status) return false;

				return true;
			}

			public override bool Equals(object obj) => Equals(obj as CustomerDTO);

			public override int GetHashCode()
			{
				var hash = new HashCode();
				hash.Add(id);
				hash.Add(name);
				hash.Add(email);
				hash.Add(status);

				return hash.ToHashCode();
			}
			#endregion Equals & HashCode 

			#region GrpcMapping
			public static Protos.CustomerIF_v1.CustomerDTO ToGrpc( ICustomerIF_v1.CustomerDTO @this )
			{
				Protos.CustomerIF_v1.CustomerDTO result = new();

				result.Id = @this.id;
				result.Name = @this.name;
				result.Email = @this.email;
				result.Status = ICustomerIF_v1.CustomerStatusesMappings.ToGrpc( @this.status );

				return result;
			}
			public static ICustomerIF_v1.CustomerDTO FromGrpc( Protos.CustomerIF_v1.CustomerDTO @from )
			{
				ICustomerIF_v1.CustomerDTO result = new();

				result.id = @from.Id;
				result.name = @from.Name;
				result.email = @from.Email;
				result.status = ICustomerIF_v1.CustomerStatusesMappings.FromGrpc( @from.Status) ;

				return result;
			}
			#endregion GrpcMapping
		}

	}
}
