// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Logging;
using Serilog.Context;
using ServiceKit.Net;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.Swagger;
using System.Linq;
using System.Net.Mime;

namespace CustomerManagement.Customers
{
	[ApiController]
	[Route( "customermanagement/customers/customerif/v1" )]
	public class CustomerIF_v1_RestController : ControllerBase 
	{
		private readonly ILogger<CustomerIF_v1_RestController> _logger;
		private readonly ICustomerIF_v1 _service;
		public CustomerIF_v1_RestController( ILogger<CustomerIF_v1_RestController> logger, ICustomerIF_v1 service )
		{
			_logger = logger; 
			_service = service; 
		}

		private static (Statuses Status, IList<ServiceKit.Net.Error> Errors) _MapFailure( Exception ex )
		{
			// a broken field is the caller's to fix, and every rule that failed is worth reporting
			if( ex is PolyPersist.Net.Common.ValidationExeption validationExeption )
				return (Statuses.BadRequest, validationExeption.ValidationErrors.Select( validationError => new ServiceKit.Net.Error() {
					Path = validationError.Path,
					MessageText = validationError.ErrorText,
					AdditionalInformation = $"{validationError.TypeOfEntity}.{validationError.MemberOfEntity}",
				} ).ToList<ServiceKit.Net.Error>());

			if( ex is PolyPersist.Net.Common.NotFoundException )
				return (Statuses.NotFound, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			if( ex is PolyPersist.Net.Common.DuplicateKeyException
				|| ex is PolyPersist.Net.Common.ConcurrencyConflictException
				|| ex is PolyPersist.Net.Common.InvalidRequestException )
				return (Statuses.BadRequest, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			// anything else really is ours: the caller can do nothing about it, so say so plainly
			return (Statuses.InternalError, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message, AdditionalInformation = ex.ToString() } });
		}

		[HttpGet( "getcustomer/{customerId}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(ICustomerIF_v1.CustomerDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> getCustomer( [FromRoute] string customerId)
		{
			using(LogContext.PushProperty( "Scope", "CustomerIF_v1.getCustomer" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.getCustomer( ctx, customerId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(Statuses.NotImplemented.ToHttp(), new List<ServiceKit.Net.Error>() { new() { MessageText = "Not handled reponse in REST Controller when calling 'CustomerIF_v1.getCustomer'" } } );
						}
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}

		[HttpPost( "registercustomer/{name}/{email}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(ICustomerIF_v1.CustomerDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> registerCustomer( [FromRoute] string name,  [FromRoute] string email)
		{
			using(LogContext.PushProperty( "Scope", "CustomerIF_v1.registerCustomer" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.registerCustomer( ctx, name, email );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(Statuses.NotImplemented.ToHttp(), new List<ServiceKit.Net.Error>() { new() { MessageText = "Not handled reponse in REST Controller when calling 'CustomerIF_v1.registerCustomer'" } } );
						}
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}
	}
}
