// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers.Protos.CustomerIF_v1;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Microsoft.Extensions.Logging;
using Serilog.Context;
using ServiceKit.Net;
using System.Linq;

namespace CustomerManagement.Customers
{
	[AutoRegisterGrpc]
	public class CustomerIF_v1_GrpcController : CustomerManagement.Customers.Protos.CustomerIF_v1.CustomerIF_v1.CustomerIF_v1Base 
	{
		private readonly ILogger<CustomerIF_v1_GrpcController> _logger;
		private readonly ICustomerIF_v1 _service;

		public CustomerIF_v1_GrpcController( ILogger<CustomerIF_v1_GrpcController> logger, ICustomerIF_v1 service )
		{
			_logger = logger; 
			_service = service; 
		}

		private static (Statuses Status, IList<ServiceKit.Net.Error> Errors) _MapFailure( Exception ex )
		{
			// a broken field is the caller's to fix, and every rule that failed is worth reporting
			if( ex is PolyPersist.Net.Common.ValidationExeption validationExeption )
				return (Statuses.BadRequest, validationExeption.ValidationErrors.Select( validationError => new ServiceKit.Net.Error() {
					Path = validationError.Path,
					MessageText = validationError.ErrorText,
					AdditionalInformation = $"{validationError.TypeOfEntity}.{validationError.MemberOfEntity}",
				} ).ToList<ServiceKit.Net.Error>());

			if( ex is PolyPersist.Net.Common.NotFoundException )
				return (Statuses.NotFound, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			if( ex is PolyPersist.Net.Common.DuplicateKeyException
				|| ex is PolyPersist.Net.Common.ConcurrencyConflictException
				|| ex is PolyPersist.Net.Common.InvalidRequestException )
				return (Statuses.BadRequest, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			// anything else really is ours: the caller can do nothing about it, so say so plainly
			return (Statuses.InternalError, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message, AdditionalInformation = ex.ToString() } });
		}

		public override async Task<CustomerIF_v1_getCustomerResponse> getCustomer( CustomerIF_v1_getCustomerRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "CustomerIF_v1.getCustomer" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string customerId;
					customerId = request.CustomerId;

					// calling the service function itself
					var response = await _service.getCustomer( ctx , customerId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new CustomerIF_v1_getCustomerResponse() { Status = ServiceKit.Protos.Statuses.Ok };
							result.Value = response.Value != null ? ICustomerIF_v1.CustomerDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return _GrpcFailure_getCustomer( Statuses.NotImplemented, new [] { new ServiceKit.Net.Error() { MessageText = "Not handled reponse in GRPC Controller when calling 'CustomerIF_v1.getCustomer'" } } );
						}
					}
					else
					{
						return _GrpcFailure_getCustomer( response.Status, response.Errors );
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return _GrpcFailure_getCustomer( failure.Status, failure.Errors );
				}
			}
		}

		private static CustomerIF_v1_getCustomerResponse _GrpcFailure_getCustomer( Statuses status, IEnumerable<ServiceKit.Net.Error> errors )
		{
			var failure = new CustomerIF_v1_getCustomerResponse() { Status = status.ToGrpc() };
			foreach( var error in errors )
				failure.Errors.Add( new ServiceKit.Protos.Error() {
					Path = error.Path ?? string.Empty,
					MessageText = error.MessageText ?? string.Empty,
					AdditionalInformation = error.AdditionalInformation ?? string.Empty,
				} );
			return failure;
		}

		public override async Task<CustomerIF_v1_registerCustomerResponse> registerCustomer( CustomerIF_v1_registerCustomerRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "CustomerIF_v1.registerCustomer" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string name;
					name = request.Name;
					string email;
					email = request.Email;

					// calling the service function itself
					var response = await _service.registerCustomer( ctx , name, email );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new CustomerIF_v1_registerCustomerResponse() { Status = ServiceKit.Protos.Statuses.Ok };
							result.Value = response.Value != null ? ICustomerIF_v1.CustomerDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return _GrpcFailure_registerCustomer( Statuses.NotImplemented, new [] { new ServiceKit.Net.Error() { MessageText = "Not handled reponse in GRPC Controller when calling 'CustomerIF_v1.registerCustomer'" } } );
						}
					}
					else
					{
						return _GrpcFailure_registerCustomer( response.Status, response.Errors );
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return _GrpcFailure_registerCustomer( failure.Status, failure.Errors );
				}
			}
		}

		private static CustomerIF_v1_registerCustomerResponse _GrpcFailure_registerCustomer( Statuses status, IEnumerable<ServiceKit.Net.Error> errors )
		{
			var failure = new CustomerIF_v1_registerCustomerResponse() { Status = status.ToGrpc() };
			foreach( var error in errors )
				failure.Errors.Add( new ServiceKit.Protos.Error() {
					Path = error.Path ?? string.Empty,
					MessageText = error.MessageText ?? string.Empty,
					AdditionalInformation = error.AdditionalInformation ?? string.Empty,
				} );
			return failure;
		}
	}
}
