
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement.Order
{
	public partial class Base
	{
		public string Id { get; set; }
		public string partionKey { get; set; }
	}

}
