
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement.Order
{
	public partial class Base
	{
		public string Id { get; set; }
		public string partionKey { get; set; }

		#region Clone & Copy 
		virtual public Base Clone()
		{
			Base clone = new();

			clone.Id = new string(Id.ToCharArray());
			clone.partionKey = new string(partionKey.ToCharArray());

			return clone;
		}
		#endregion Clone & Copy 
	}

}
