
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement.Order
{
	public partial class Base : IEquatable<Base>
	{
		public string Id { get; set; }
		public string partionKey { get; set; }

		#region Clone 
		public virtual Base Clone()
		{
			Base clone = new();

			clone.Id = new string(Id.ToCharArray());
			clone.partionKey = new string(partionKey.ToCharArray());

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( Base other )
		{
			if (other is null) return false;

			if(Id != other.Id) return false;
			if(partionKey != other.partionKey) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as Base);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			hash.Add(Id);
			hash.Add(partionKey);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
