
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement
{

	public partial interface ISalesDocument
	{
		public string humanKey { get; set; }
		public string partnerData { get; set; }
	}
}
