// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Sales.OrderManagement
{

	/// A reusable field group: everything that is a sales document carries these, so the fields
	/// are declared once and inherited rather than repeated.
	public partial interface ISalesDocument
	{
		public string humanKey { get; set; }
		public string partnerData { get; set; }
	}
}
