// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Sales.OrderManagement.Order
{
	public enum OrderStatuses
	{
		Draft,
		Released,
		Finished,
		Canceled,
	}
}
