
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement.Order
{
	public class OrderItem
	{
		public string productId { get; set; }
		public string productName { get; set; }
		public decimal quantity { get; set; }
		public string UnitPrice { get; set; }
		public string subTotalPrice { get; set; }
	}
}
