// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist;
using PolyPersist.Net.Common;

namespace Sales.OrderManagement.Order
{
	public partial class OrderItem : IEquatable<OrderItem>, IValidable
	{
		public string productId { get; set; }
		public string productName { get; set; }
		public decimal quantity { get; set; }
		public decimal unitPrice { get; set; }
		public decimal subTotalPrice { get; set; }

		#region Clone 
		public virtual OrderItem Clone()
		{
			OrderItem clone = new();

			clone.productId = new string(productId.ToCharArray());
			clone.productName = new string(productName.ToCharArray());
			clone.quantity = quantity;
			clone.unitPrice = unitPrice;
			clone.subTotalPrice = subTotalPrice;

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( OrderItem other )
		{
			if (other is null) return false;

			if(productId != other.productId) return false;
			if(productName != other.productName) return false;
			if(quantity != other.quantity) return false;
			if(unitPrice != other.unitPrice) return false;
			if(subTotalPrice != other.subTotalPrice) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as OrderItem);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			hash.Add(productId);
			hash.Add(productName);
			hash.Add(quantity);
			hash.Add(unitPrice);
			hash.Add(subTotalPrice);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 

		#region Validation
		public virtual bool Validate( IList<IValidationError> errors )
		{
			int before = errors.Count;

			if (quantity <= 0)
				errors.Add( new ValidationError { TypeOfEntity = "OrderItem", MemberOfEntity = "quantity", ErrorText = "quantity must satisfy: value > 0" } );

			if (unitPrice < 0)
				errors.Add( new ValidationError { TypeOfEntity = "OrderItem", MemberOfEntity = "unitPrice", ErrorText = "unitPrice must satisfy: value >= 0" } );

			if (subTotalPrice < 0)
				errors.Add( new ValidationError { TypeOfEntity = "OrderItem", MemberOfEntity = "subTotalPrice", ErrorText = "subTotalPrice must satisfy: value >= 0" } );

			return errors.Count == before;
		}
		#endregion Validation
	}

}
