
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Sales.OrderManagement;

namespace Sales.OrderManagement.Order
{
	public partial class OrderHeader
	{
		public string customerId { get; set; }
		public DateOnly orderingDate { get; set; }
		public OrderStatuses status { get; set; }
		public decimal totalPrice { get; set; }
		public List<DateOnly> datelist { get; set; }
		public List<OrderItem> items { get; set; }
	}
}
