// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist;
using PolyPersist.Net.Common;
using PolyPersist.Net.Core;
using Sales.OrderManagement;

namespace Sales.OrderManagement.Order
{
	public partial class OrderHeader : Core.Base.IBaseEntity, ISalesDocument, IEquatable<OrderHeader>, IValidable
	{
		#region IBaseEntity
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBaseEntity

		#region ISalesDocument
		public string humanKey { get; set; }
		public string partnerData { get; set; }
		#endregion ISalesDocument

		/// Another aggregate is referenced by identity, never embedded. The .NET emitter turns
		/// this into a typed EntityId, so handing over an order id where a customer id belongs
		/// stops being a runtime mystery and becomes a compile error.
		public EntityId<CustomerManagement.Customers.Customer.CustomerAccount> customer { get; set; }
		public DateOnly orderingDate { get; set; }
		public OrderStatuses status { get; set; }
		public decimal totalPrice { get; set; }
		public List<OrderItem> items { get; set; } = new();

		#region Clone 
		public virtual OrderHeader Clone()
		{
			OrderHeader clone = new();

			// begin: BaseEntity
			// end: BaseEntity

			// begin: SalesDocument
			clone.humanKey = new string(humanKey.ToCharArray());
			clone.partnerData = new string(partnerData.ToCharArray());
			// end: SalesDocument

			clone.customer = customer;
			clone.orderingDate = orderingDate;
			clone.status = status;
			clone.totalPrice = totalPrice;

			// clone of items
			clone.items.AddRange( items.Select( v => v.Clone() ));

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( OrderHeader other )
		{
			if (other is null) return false;

			// begin: BaseEntity
			// end: BaseEntity

			// begin: SalesDocument
			if(humanKey != other.humanKey) return false;
			if(partnerData != other.partnerData) return false;
			// end: SalesDocument


			// equals of customer
			if(customer == null && other.customer != null ) return false;
			if(customer != null && customer.Equals(other.customer) == false ) return false;
			if(orderingDate != other.orderingDate) return false;
			if(status != other.status) return false;
			if(totalPrice != other.totalPrice) return false;

			// equals of items
			if(items.SequenceEqual(other.items) == false ) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as OrderHeader);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: BaseEntity
			hash.Add(id);
			hash.Add(etag);
			hash.Add(LastUpdate);
			// end: BaseEntity

			// begin: SalesDocument
			hash.Add(humanKey);
			hash.Add(partnerData);
			// end: SalesDocument


			// hash of customer
			if(customer != null ) hash.Add(customer);
			hash.Add(orderingDate);
			hash.Add(status);
			hash.Add(totalPrice);

			// hash of items
			foreach( var element_items in items)
				hash.Add(element_items);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 

		#region Validation
		public virtual bool Validate( IList<IValidationError> errors )
		{
			int before = errors.Count;
			ValidateInto( errors, string.Empty );
			return errors.Count == before;
		}

		public virtual void ValidateInto( IList<IValidationError> errors, string pathPrefix )
		{
			if (totalPrice < 0)
				errors.Add( new ValidationError { TypeOfEntity = "OrderHeader", MemberOfEntity = "totalPrice", Path = pathPrefix + "totalPrice", ErrorText = "totalPrice must satisfy: value >= 0" } );

			if (items != null)
			{
				for (int index = 0; index < items.Count; index++)
					items[index]?.ValidateInto( errors, $"{pathPrefix}items[{index}]." );
			}
		}
		#endregion Validation
	}

}
