<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="PolyPersist.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Base\Models\Core.Base.Models.csproj" />
    <ProjectReference Include="..\..\..\CustomerManagement\Customers\Models\CustomerManagement.Customers.Models.csproj" />
  </ItemGroup>

</Project>
