
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Google.Protobuf.Collections;
using Sales.OrderManagement;
using System.Globalization;

namespace Sales.OrderManagement
{
	public partial class OrderItemDTO
	{
		public static Protos.OrderItemDTO ToGrpc( OrderItemDTO @this )
		{
			Protos.OrderItemDTO result = new();

			result.ProductId = @this.productId;
			result.ProductName = @this.productName;
			result.Quantity = @this.quantity.ToString(CultureInfo.InvariantCulture);
			result.UnitPrice = @this.UnitPrice.ToString(CultureInfo.InvariantCulture);
			result.SubTotalPrice = @this.subTotalPrice;

			return result;
		}
		public static OrderItemDTO FromGrpc( Protos.OrderItemDTO @from )
		{
			OrderItemDTO result = new();

			result.productId = @from.ProductId;
			result.productName = @from.ProductName;
			result.quantity = decimal.Parse(@from.Quantity, CultureInfo.InvariantCulture);
			result.UnitPrice = decimal.Parse(@from.UnitPrice, CultureInfo.InvariantCulture);
			result.subTotalPrice = @from.SubTotalPrice;

			return result;
		}
	}
	public partial class OrderDTO
	{
		public static Protos.OrderDTO ToGrpc( OrderDTO @this )
		{
			Protos.OrderDTO result = new();

			result.CustomerId = @this.customerId;
			result.OrderingDate = @this.orderingDate;
			result.TotalPrice = @this.totalPrice.ToString(CultureInfo.InvariantCulture);
			result.Items.AddRange( @this.items.Select( v => OrderItemDTO.ToGrpc( v ) ));

			return result;
		}
		public static OrderDTO FromGrpc( Protos.OrderDTO @from )
		{
			OrderDTO result = new();

			result.customerId = @from.CustomerId;
			result.orderingDate = @from.OrderingDate;
			result.totalPrice = decimal.Parse(@from.TotalPrice, CultureInfo.InvariantCulture);
			result.items.AddRange( @from.Items.Select( v => OrderItemDTO.FromGrpc(v) ));

			return result;
		}
	}
	public partial interface IOrderIF_v1
	{
	}
}
