// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using ServiceKit.Net;
using System.Net;
using System.Net.Http.Json;

namespace BFF.ApiClientKit
{
	static partial class Rest 
	{
		static class CustomerIF
		{
			static class V1 
			{
				public static async Task<Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>> getCustomer(string customerId)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, WebUtility.UrlEncode( $"/customermanagement/customers/customerif/v1/getcustomer/{customerId}" ) );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "CustomerManagement.Customers.CustomerIF.V1.getCustomer" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>();
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var error = await response.Content.ReadFromJsonAsync<Error>();
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( error );
						}
						else
						{
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
								Status = response.StatusCode.FromHttp(),
								MessageText = "Not handled reponse in REST client when calling 'CustomerIF_v1_getCustomer'",
							} );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>> registerCustomer(string name, string email)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, WebUtility.UrlEncode( $"/customermanagement/customers/customerif/v1/registercustomer/{name}/{email}" ) );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "CustomerManagement.Customers.CustomerIF.V1.registerCustomer" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>();
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var error = await response.Content.ReadFromJsonAsync<Error>();
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( error );
						}
						else
						{
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
								Status = response.StatusCode.FromHttp(),
								MessageText = "Not handled reponse in REST client when calling 'CustomerIF_v1_registerCustomer'",
							} );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

			}
		}
	}
}
