// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using ServiceKit.Net;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace BFF.ApiClientKit
{
	static partial class Rest 
	{
		static class CustomerIF
		{
			static class V1 
			{
				// the same options the host is configured with: web defaults, and enums by name
				private static readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions( JsonSerializerDefaults.Web )
				{
					Converters = { new JsonStringEnumConverter() },
				};
				public static async Task<Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>> getCustomer(string customerId)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, $"/customermanagement/customers/customerif/v1/getcustomer/{Uri.EscapeDataString(customerId)}" );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "CustomerManagement.Customers.CustomerIF.V1.getCustomer" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>( _jsonOptions );
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
						}
						else
						{
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'CustomerIF_v1_getCustomer'" );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>> registerCustomer(string name, string email)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/customermanagement/customers/customerif/v1/registercustomer/{Uri.EscapeDataString(name)}/{Uri.EscapeDataString(email)}" );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "CustomerManagement.Customers.CustomerIF.V1.registerCustomer" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>( _jsonOptions );
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
						}
						else
						{
							return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'CustomerIF_v1_registerCustomer'" );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<CustomerManagement.Customers.ICustomerIF_v1.CustomerDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

			}
		}
	}
}
