
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
syntax = "proto3";

option csharp_namespace = "Sales.Tracking";

package OrderTrackingEntryPackage;

import "google/protobuf/empty.proto";
import "servicekit_error.proto";

	message OrderItem {
		string productId = 1
		string productName = 2
		decimal quantity = 3
		string UnitPrice = 4
		string subTotalPrice = 5
	}
