// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using PolyPersist.Net.Core;
using Sales.Tracking;

namespace Sales.Tracking.OrderTrackingEntry
{
	public partial class TrackingEntry : Core.Base.IBaseEntity, IEquatable<TrackingEntry>
	{
		#region IBaseEntity
		/// The identity is also the ordering scope: facts an aggregate records travel under the
		/// aggregate's own id, so the outside world sees one order's facts in the order they
		/// happened - and sees nothing about the order between two different orders, because no
		/// such order exists.
		public string id { get; set; } = null!;
		public string etag { get; set; } = null!;
		public DateTime LastUpdate { get; set; }
		#endregion IBaseEntity

		public EntityId<Sales.OrderManagement.Order.OrderHeader> order { get; set; }
		public Sales.Tracking.TrackingStatuses trackingStatus { get; set; }
		public DateTime statusDate { get; set; }

		#region Clone 
		public virtual TrackingEntry Clone()
		{
			TrackingEntry clone = new();

			// begin: BaseEntity
			// end: BaseEntity

			clone.order = order;
			clone.trackingStatus = trackingStatus;
			clone.statusDate = statusDate;

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( TrackingEntry? other )
		{
			if (other is null) return false;

			// begin: BaseEntity
			// end: BaseEntity

			if(order != other.order) return false;
			if(trackingStatus != other.trackingStatus) return false;
			if(statusDate != other.statusDate) return false;

			return true;
		}

		public override bool Equals(object? obj) => Equals(obj as TrackingEntry);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: BaseEntity
			// end: BaseEntity

			hash.Add(order);
			hash.Add(trackingStatus);
			hash.Add(statusDate);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 
	}

}
