
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.Tracking.OrderTrackingEntry
{
	using PolyPersist.Net.Core;

	public partial class TrackingEntry : Entity
	{
		public TrackingStatuses TrackingStatus { get; set; }
		public string statusDate { get; set; }
		public string orderId { get; set; }
	}
}
