// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Grpc.Net.Client;
using Sales.OrderManagement;
using Sales.OrderManagement.Protos.OrderIF_v1;
using ServiceKit.Net;
using System.Globalization;
using System.Linq;

namespace BFF.ApiClientKit
{
	static partial class Grpc 
	{
		/// The published surface of orders: DTOs only, no domain type ever reaches the wire.
		static class OrderIF
		{
			static class V1 
			{
				private static OrderIF_v1.OrderIF_v1Client _client;
				public static async Task<Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>> getOrder(string orderId)
				{
					try
					{
						// fill grpc request
						var request = new OrderIF_v1_getOrderRequest();
						request.OrderId = orderId;

						// calling grpc client
						_client ??= new OrderIF_v1.OrderIF_v1Client(GrpClient._channel);
						var grpc_response = await _client.getOrderAsync( request, new CallOptions(GrpClient.GetMetadata( "Sales.OrderManagement.OrderIF_v1.getOrder" ))).ResponseAsync;

						// fill response
						if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

						if( grpc_response.ResultCase == OrderIF_v1_getOrderResponse.ResultOneofCase.Value )
						{
							Sales.OrderManagement.IOrderIF_v1.OrderDTO value;
							value = grpc_response.Value != null ? Sales.OrderManagement.IOrderIF_v1.OrderDTO.FromGrpc( grpc_response.Value ) : null;
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Success( value );
						}

						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'OrderIF_v1_getOrder'" );
					}
					catch (RpcException ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>> placeOrder(Sales.OrderManagement.IOrderIF_v1.OrderDTO order)
				{
					try
					{
						// fill grpc request
						var request = new OrderIF_v1_placeOrderRequest();
						request.Order = order != null ? Sales.OrderManagement.IOrderIF_v1.OrderDTO.ToGrpc( order ) : null;

						// calling grpc client
						_client ??= new OrderIF_v1.OrderIF_v1Client(GrpClient._channel);
						var grpc_response = await _client.placeOrderAsync( request, new CallOptions(GrpClient.GetMetadata( "Sales.OrderManagement.OrderIF_v1.placeOrder" ))).ResponseAsync;

						// fill response
						if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

						if( grpc_response.ResultCase == OrderIF_v1_placeOrderResponse.ResultOneofCase.Value )
						{
							Sales.OrderManagement.IOrderIF_v1.OrderDTO value;
							value = grpc_response.Value != null ? Sales.OrderManagement.IOrderIF_v1.OrderDTO.FromGrpc( grpc_response.Value ) : null;
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Success( value );
						}

						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'OrderIF_v1_placeOrder'" );
					}
					catch (RpcException ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>> setPrice(Sales.OrderManagement.IOrderIF_v1.OrderItemDTO orderItem, decimal price)
				{
					try
					{
						// fill grpc request
						var request = new OrderIF_v1_setPriceRequest();
						request.OrderItem = orderItem != null ? Sales.OrderManagement.IOrderIF_v1.OrderItemDTO.ToGrpc( orderItem ) : null;
						request.Price = price.ToString(CultureInfo.InvariantCulture);

						// calling grpc client
						_client ??= new OrderIF_v1.OrderIF_v1Client(GrpClient._channel);
						var grpc_response = await _client.setPriceAsync( request, new CallOptions(GrpClient.GetMetadata( "Sales.OrderManagement.OrderIF_v1.setPrice" ))).ResponseAsync;

						// fill response
						if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

						if( grpc_response.ResultCase == OrderIF_v1_setPriceResponse.ResultOneofCase.Value )
						{
							Sales.OrderManagement.IOrderIF_v1.OrderItemDTO value;
							value = grpc_response.Value != null ? Sales.OrderManagement.IOrderIF_v1.OrderItemDTO.FromGrpc( grpc_response.Value ) : null;
							return Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>.Success( value );
						}

						return Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'OrderIF_v1_setPrice'" );
					}
					catch (RpcException ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v1.OrderItemDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response> justOrder(string orderId)
				{
					try
					{
						// fill grpc request
						var request = new OrderIF_v1_justOrderRequest();
						request.OrderId = orderId;

						// calling grpc client
						_client ??= new OrderIF_v1.OrderIF_v1Client(GrpClient._channel);
						var grpc_response = await _client.justOrderAsync( request, new CallOptions(GrpClient.GetMetadata( "Sales.OrderManagement.OrderIF_v1.justOrder" ))).ResponseAsync;

						// fill response
						if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
							return Response.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

						return Response.Success();
					}
					catch (RpcException ex)
					{
						return Response.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}


				private static ServiceKit.Net.Error[] _FromGrpcErrors( IEnumerable<ServiceKit.Protos.Error> errors )
				{
					return errors.Select( error => new ServiceKit.Net.Error() {
						Path = error.Path,
						MessageText = error.MessageText,
						AdditionalInformation = error.AdditionalInformation,
					} ).ToArray();
				}
			}
		}
	}
}
