// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace BFF.ApiClientKit
{
	/// The second version lives next to the first on purpose: this is how a published interface is
	/// carried forward without breaking the callers still on v1.
	static partial class Rest 
	{
		/// The second version lives next to the first on purpose: this is how a published interface is
		/// carried forward without breaking the callers still on v1.
		static class OrderIF
		{
			static class V2 
			{
				// the same options the host is configured with: web defaults, and enums by name
				private static readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions( JsonSerializerDefaults.Web )
				{
					Converters = { new JsonStringEnumConverter() },
				};
				public static async Task<Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>> getOrder(string orderId)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, $"/sales/ordermanagement/orderif/v2/getorder/{Uri.EscapeDataString(orderId)}" );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "Sales.OrderManagement.OrderIF.V2.getOrder" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<Sales.OrderManagement.IOrderIF_v2.OrderDTO>( _jsonOptions );
							if (value is null)
								return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, "The server answered 'getOrder' with a success status and an empty body." );

							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
						}
						else
						{
							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_getOrder'" );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>> placeOrder(Sales.OrderManagement.IOrderIF_v2.OrderDTO order)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v2/placeorder" );

						// build content
						request.Content = new StringContent( JsonSerializer.Serialize<Sales.OrderManagement.IOrderIF_v2.OrderDTO>( order, _jsonOptions ), Encoding.UTF8, "application/json" );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "Sales.OrderManagement.OrderIF.V2.placeOrder" );

						if (response.IsSuccessStatusCode)
						{
							var value = await response.Content.ReadFromJsonAsync<Sales.OrderManagement.IOrderIF_v2.OrderDTO>( _jsonOptions );
							if (value is null)
								return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, "The server answered 'placeOrder' with a success status and an empty body." );

							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Success( value );
						}
						else if( response.Content != null )
						{
							var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
						}
						else
						{
							return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_placeOrder'" );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response<Sales.OrderManagement.IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

				public static async Task<Response> justOrder(string orderId)
				{
					try
					{
						// build request
						HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v2/justorder/{Uri.EscapeDataString(orderId)}" );

						// call rest client 
						HttpResponseMessage response = await RestClient.Request( request, "Sales.OrderManagement.OrderIF.V2.justOrder" );

						if (response.IsSuccessStatusCode)
						{
							return Response.Success();
						}
						else if( response.Content != null )
						{
							var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
							return Response.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
						}
						else
						{
							return Response.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_justOrder'" );
						}
					}
					catch (HttpRequestException ex)
					{
						return Response.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
					catch (Exception ex)
					{
						return Response.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString(),
						} );
					}
				}

			}
		}
	}
}
