
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using System.Globalization;

namespace Sales.OrderManagement.Order
{
	public partial class OrderItem
	{
		public static Protos.OrderItem ToGrpc( OrderItem @this )
		{
			Protos.OrderItem result = new();

			result.ProductId = @this.productId;
			result.ProductName = @this.productName;
			result.Quantity = @this.quantity.ToString(CultureInfo.InvariantCulture);
			result.UnitPrice = @this.UnitPrice.ToString(CultureInfo.InvariantCulture);
			result.SubTotalPrice = @this.subTotalPrice;

			return result;
		}
		public static OrderItem FromGrpc( Protos.OrderItem @from )
		{
			OrderItem result = new();

			result.productId = @from.ProductId;
			result.productName = @from.ProductName;
			result.quantity = decimal.Parse(@from.Quantity, CultureInfo.InvariantCulture);
			result.UnitPrice = decimal.Parse(@from.UnitPrice, CultureInfo.InvariantCulture);
			result.subTotalPrice = @from.SubTotalPrice;

			return result;
		}
	}
}
