
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.OrderManagement.Order
{
	public static class OrderStatusesExtensions
	{
		public static Protos.OrderStatuses ToGrpc( this OrderStatuses @this )
		{
			return @this switch
			{
				OrderStatuses.Draft => Protos.OrderStatuses.Draft,
				OrderStatuses.Released => Protos.OrderStatuses.Released,
				OrderStatuses.Finished => Protos.OrderStatuses.Finished,
				OrderStatuses.Canceled => Protos.OrderStatuses.Canceled,
				_ => throw new NotImplementedException(), 
			};
		}

		public static OrderStatuses ToDotnet( this Protos.OrderStatuses @this )
		{
			return @this switch
			{
				Protos.OrderStatuses.Draft => OrderStatuses.Draft,
				Protos.OrderStatuses.Released => OrderStatuses.Released,
				Protos.OrderStatuses.Finished => OrderStatuses.Finished,
				Protos.OrderStatuses.Canceled => OrderStatuses.Canceled,
				_ => throw new NotImplementedException(), 
			};
		}

	}
}
