
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Google.Protobuf.Collections;
using Sales.OrderManagement;
using System.Globalization;

namespace Sales.OrderManagement.Order
{
	public partial class OrderHeader
	{
		public Protos.OrderHeader ToGrpc()
		{
			Protos.OrderHeader result = new();

			result.CustomerId = customerId;
			result.OrderingDate = orderingDate.ToString(CultureInfo.InvariantCulture);
			result.Status = status.ToGrpc();
			result.TotalPrice = totalPrice.ToString(CultureInfo.InvariantCulture);
			result.Datelist.AddRange( datelist.Select( v => v.ToString(CultureInfo.InvariantCulture) ));
			result.Items.AddRange( items.Select( v => v.ToGrpc() ));

			return result;
		}
		public static OrderHeader FromGrpc( Protos.OrderHeader @from )
		{
			OrderHeader result = new();

			result.customerId = @from.CustomerId;
			result.orderingDate = DateOnly.Parse(@from.OrderingDate, CultureInfo.InvariantCulture);
			result.status = @from.Status.ToDotnet();
			result.totalPrice = decimal.Parse(@from.TotalPrice, CultureInfo.InvariantCulture);
			result.datelist.AddRange( @from.Datelist.Select( v => DateOnly.Parse(v, CultureInfo.InvariantCulture) ));
			result.items.AddRange( @from.Items.Select( v => OrderItem.FromGrpc(v) ));

			return result;
		}
	}
}
