
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.Tracking.OrderTrackingEntry
{
	public partial class TrackingEntry
	{
		public Protos.TrackingEntry ToGrpc()
		{
			Protos.TrackingEntry result = new();

			result.TrackingStatus = TrackingStatus.ToGrpc();
			result.StatusDate = statusDate;
			result.OrderId = orderId;

			return result;
		}
	}
}
