
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>


namespace Sales.Tracking
{
	public static class TrackingStatusesExtensions
	{
		public static Protos.TrackingStatuses ToGrpc( this TrackingStatuses @this )
		{
			return @this switch
			{
				TrackingStatuses.Pending => Protos.TrackingStatuses.Pending,
				TrackingStatuses.Confirmed => Protos.TrackingStatuses.Confirmed,
				TrackingStatuses.Processing => Protos.TrackingStatuses.Processing,
				TrackingStatuses.ReadyForPickup => Protos.TrackingStatuses.ReadyForPickup,
				TrackingStatuses.Shipped => Protos.TrackingStatuses.Shipped,
				TrackingStatuses.InTransit => Protos.TrackingStatuses.InTransit,
				TrackingStatuses.OutForDelivery => Protos.TrackingStatuses.OutForDelivery,
				TrackingStatuses.Delivered => Protos.TrackingStatuses.Delivered,
				TrackingStatuses.FailedDelivery => Protos.TrackingStatuses.FailedDelivery,
				TrackingStatuses.Returned => Protos.TrackingStatuses.Returned,
				TrackingStatuses.Cancelled => Protos.TrackingStatuses.Cancelled,
				_ => throw new NotImplementedException(), 
			};
		}

		public static TrackingStatuses FromGrpc( this Protos.TrackingStatuses @this )
		{
			return @this switch
			{
				Protos.TrackingStatuses.Pending => TrackingStatuses.Pending,
				Protos.TrackingStatuses.Confirmed => TrackingStatuses.Confirmed,
				Protos.TrackingStatuses.Processing => TrackingStatuses.Processing,
				Protos.TrackingStatuses.ReadyForPickup => TrackingStatuses.ReadyForPickup,
				Protos.TrackingStatuses.Shipped => TrackingStatuses.Shipped,
				Protos.TrackingStatuses.InTransit => TrackingStatuses.InTransit,
				Protos.TrackingStatuses.OutForDelivery => TrackingStatuses.OutForDelivery,
				Protos.TrackingStatuses.Delivered => TrackingStatuses.Delivered,
				Protos.TrackingStatuses.FailedDelivery => TrackingStatuses.FailedDelivery,
				Protos.TrackingStatuses.Returned => TrackingStatuses.Returned,
				Protos.TrackingStatuses.Cancelled => TrackingStatuses.Cancelled,
				_ => throw new NotImplementedException(), 
			};
		}

	}
}
