// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Temporalio.Common;
using Temporalio.Workflows;

namespace Sales.OrderManagement
{

	/// <summary>
	/// The activity options of the steps of workflow 'FulfilOrder'.
	/// </summary>
	public static partial class FulfilOrderDefaults
	{
		/// <summary>The ceiling of a single attempt. Technical, not a business property, so it is not modelled.</summary>
		public static TimeSpan DefaultStartToCloseTimeout { get; set; } = TimeSpan.FromMinutes(1);

		public static ActivityOptions For(string stepName)
		{
			var options = new ActivityOptions
			{
				StartToCloseTimeout = DefaultStartToCloseTimeout,
			};

			switch (stepName)
			{
				case "reserveStock":
					options.ScheduleToCloseTimeout = TimeSpan.FromSeconds(600);
					options.RetryPolicy = new RetryPolicy { MaximumAttempts = 3 };
					break;
				case "releaseStock":
					options.ScheduleToCloseTimeout = TimeSpan.FromSeconds(600);
					options.RetryPolicy = new RetryPolicy { MaximumAttempts = 3 };
					break;
				case "chargeCard":
					options.ScheduleToCloseTimeout = TimeSpan.FromSeconds(30);
					options.RetryPolicy = new RetryPolicy { MaximumAttempts = 1 };
					break;
				case "refundCard":
					options.ScheduleToCloseTimeout = TimeSpan.FromSeconds(600);
					options.RetryPolicy = new RetryPolicy { MaximumAttempts = 3 };
					break;
				case "shipOrder":
					options.ScheduleToCloseTimeout = TimeSpan.FromSeconds(600);
					options.RetryPolicy = new RetryPolicy { MaximumAttempts = 3 };
					break;
			}

			Customize(stepName, options);
			return options;
		}

		/// <summary>Implement this in your own partial to override anything above.</summary>
		static partial void Customize(string stepName, ActivityOptions options);
	}
}
