// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using ServiceKit.Net;

namespace Sales.OrderManagement
{

	/// <summary>
	/// Registers workflow 'FulfilOrder' with the worker host.
	/// </summary>
	public static partial class FulfilOrderRegistration
	{
		/// <summary>
		/// Derived per workflow. Hand two workflows the same name and one worker serves both -
		/// splitting a shared queue later is a migration, merging separate ones is free.
		/// </summary>
		public const string TaskQueue = "OrderManagement.FulfilOrder";

		public static WorkflowRegistry Register(WorkflowRegistry registry, string taskQueue = TaskQueue)
		{
			return registry.Register<FulfilOrderWorkflow>(taskQueue, typeof(IFulfilOrderActivities));
		}
	}
}
