// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist.Net.Core;
using ServiceKit.Net;
using Temporalio.Workflows;

namespace Sales.OrderManagement
{

	/// Fulfilling an order is long running and it can fail halfway: the stock is reserved, then
	/// the card is charged, then the parcel ships. The model declares WHICH steps exist and what
	/// undoes each one - it deliberately does not declare their order, because a set of steps is
	/// all a model can honestly say. The developer writes the sequence; the generated step facade
	/// records every compensation and rolls them back in reverse when something throws.
	[Workflow]
	public partial class FulfilOrderWorkflow
	{
		private readonly WorkflowSaga _saga = new();

		/// <summary>Call the steps through this: it runs the activity AND records its rollback.</summary>
		protected FulfilOrderSteps Steps { get; }

		public FulfilOrderWorkflow()
		{
			Steps = new FulfilOrderSteps(_saga);
		}

		[WorkflowRun]
		public async Task<string> fulfil(EntityId<Order.OrderHeader> order, string sku, decimal quantity, decimal amount, string shippingAddress)
		{
			try
			{
				return await OnFulfil(order, sku, quantity, amount, shippingAddress);
			}
			catch (Exception failure)
			{
				// the failure is handed over, so it survives as the InnerException even when a compensation fails too
				await _saga.CompensateAsync(failure);
				throw;
			}
		}

		/// No return value, so the caller cannot be answered: this is a signal.
		[WorkflowSignal]
		public Task cancel(string reason) => OnCancel(reason);

		/// A query is read-only and synchronous - it may not await anything.
		[WorkflowQuery]
		public string status() => OnStatus();

		// The other half of the partial: this is what you write. The model declares which steps
		// exist, not in what order - so the body is yours, and the compiler will not let you forget it.
		private partial Task<string> OnFulfil(EntityId<Order.OrderHeader> order, string sku, decimal quantity, decimal amount, string shippingAddress);
		private partial Task OnCancel(string reason);
		private partial string OnStatus();
	}

	/// <summary>
	/// The typed, saga-aware steps of workflow 'FulfilOrder'. Calling a step here runs the
	/// activity and records its compensation, so a later failure rolls it back automatically.
	/// </summary>
	public sealed partial class FulfilOrderSteps
	{
		private readonly WorkflowSaga _saga;

		internal FulfilOrderSteps(WorkflowSaga saga)
		{
			_saga = saga;
		}

		public async Task<string> reserveStock(EntityId<Order.OrderHeader> order, string sku, decimal quantity)
		{
			var result = await Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.reserveStock(order, sku, quantity),
				FulfilOrderDefaults.For(nameof(reserveStock)));

			// the compensation arguments are bound from the step's own parameters and return value
			_saga.Push(nameof(reserveStock), () => Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.releaseStock(order, sku, result),
				FulfilOrderDefaults.For(nameof(IFulfilOrderActivities.releaseStock))));

			return result;
		}

		public Task releaseStock(EntityId<Order.OrderHeader> order, string sku, string reservationId)
		{
			return Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.releaseStock(order, sku, reservationId),
				FulfilOrderDefaults.For(nameof(releaseStock)));
		}

		/// A card charge is not idempotent, so one attempt only - and the money must not be left
		/// in limbo, hence the short deadline. Both are business properties, so both are modelled.
		public async Task<string> chargeCard(EntityId<Order.OrderHeader> order, decimal amount)
		{
			var result = await Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.chargeCard(order, amount),
				FulfilOrderDefaults.For(nameof(chargeCard)));

			// the compensation arguments are bound from the step's own parameters and return value
			_saga.Push(nameof(chargeCard), () => Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.refundCard(order, result),
				FulfilOrderDefaults.For(nameof(IFulfilOrderActivities.refundCard))));

			return result;
		}

		public Task refundCard(EntityId<Order.OrderHeader> order, string chargeId)
		{
			return Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.refundCard(order, chargeId),
				FulfilOrderDefaults.For(nameof(refundCard)));
		}

		/// Nothing compensates shipping: once the parcel is gone, it is gone. The absence of a
		/// compensate is itself the statement.
		public Task<string> shipOrder(EntityId<Order.OrderHeader> order, string shippingAddress)
		{
			return Workflow.ExecuteActivityAsync(
				(IFulfilOrderActivities activities) => activities.shipOrder(order, shippingAddress),
				FulfilOrderDefaults.For(nameof(shipOrder)));
		}
	}
}
