// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist.Net.Core;
using Temporalio.Activities;

namespace Sales.OrderManagement
{

	/// <summary>
	/// The activities of workflow 'FulfilOrder'. Implement this interface and register the
	/// implementation as a singleton - the worker resolves it from the service container.
	/// </summary>
	public partial interface IFulfilOrderActivities
	{
		[Activity]
		Task<string> reserveStock(EntityId<Order.OrderHeader> order, string sku, decimal quantity);

		[Activity]
		Task releaseStock(EntityId<Order.OrderHeader> order, string sku, string reservationId);

		/// A card charge is not idempotent, so one attempt only - and the money must not be left
		/// in limbo, hence the short deadline. Both are business properties, so both are modelled.
		[Activity]
		Task<string> chargeCard(EntityId<Order.OrderHeader> order, decimal amount);

		[Activity]
		Task refundCard(EntityId<Order.OrderHeader> order, string chargeId);

		/// Nothing compensates shipping: once the parcel is gone, it is gone. The absence of a
		/// compensate is itself the statement.
		[Activity]
		Task<string> shipOrder(EntityId<Order.OrderHeader> order, string shippingAddress);
	}
}
