
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Google.Protobuf.Collections;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Globalization;

namespace Sales.OrderManagement
{
	/// public interface for Orders
	/// only for service-service communication
	public partial interface IOrderIF_v1
	{
		/// <return>OrderItemDTO</return>
		public Task<Response<OrderItemDTO>> setPrice(CallingContext ctx, OrderItemDTO orderItem, decimal price);

		/// <return>OrderDTO</return>
		public Task<Response<OrderDTO>> multiPart(CallingContext ctx, OrderDTO order, OrderItemDTO orderitem);

		/// <summary>
		/// getting the order based on id
		/// </summary>
		/// <return>OrderDTO</return>
		public Task<Response<OrderDTO>> getOrder(CallingContext ctx, string orderId);

		/// <return>OrderDTO</return>
		public Task<Response<OrderDTO>> placeOrder(CallingContext ctx, OrderDTO order);

		public Task<Response> justOrder(CallingContext ctx, string orderId);


		public partial class OrderPlaced_v1
		{
			public string orderId { get; set; }

			#region Clone & Copy 
			virtual public OrderPlaced_v1 Clone()
			{
				OrderPlaced_v1 clone = new();

				clone.orderId = new string(orderId.ToCharArray());

				return clone;
			}
			#endregion Clone & Copy 
		}

		public enum OrderStatuses
		{
			Draft,
			Released,
			Finished,
			Canceled,
		}
		#region GrpcMapping
		public static class OrderStatusesMappings
		{
			public static Protos.OrderIF_v1.OrderStatuses ToGrpc( IOrderIF_v1.OrderStatuses @this )
			{
				return @this switch
				{
					IOrderIF_v1.OrderStatuses.Draft => Protos.OrderIF_v1.OrderStatuses.Draft,
					IOrderIF_v1.OrderStatuses.Released => Protos.OrderIF_v1.OrderStatuses.Released,
					IOrderIF_v1.OrderStatuses.Finished => Protos.OrderIF_v1.OrderStatuses.Finished,
					IOrderIF_v1.OrderStatuses.Canceled => Protos.OrderIF_v1.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

			public static IOrderIF_v1.OrderStatuses FromGrpc( Protos.OrderIF_v1.OrderStatuses @this )
			{
				return @this switch
				{
					Protos.OrderIF_v1.OrderStatuses.Draft => IOrderIF_v1.OrderStatuses.Draft,
					Protos.OrderIF_v1.OrderStatuses.Released => IOrderIF_v1.OrderStatuses.Released,
					Protos.OrderIF_v1.OrderStatuses.Finished => IOrderIF_v1.OrderStatuses.Finished,
					Protos.OrderIF_v1.OrderStatuses.Canceled => IOrderIF_v1.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

		}
		#endregion GrpcMapping
		public partial class OrderItemDTO
		{
			public enum DeliveryStatuses
			{
				NotDelivered,
				PartiallyDelivered,
				Delivered,
			}
			#region GrpcMapping
			public static class DeliveryStatusesMappings
			{
				public static Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses ToGrpc( IOrderIF_v1.OrderItemDTO.DeliveryStatuses @this )
				{
					return @this switch
					{
						IOrderIF_v1.OrderItemDTO.DeliveryStatuses.NotDelivered => Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.NotDelivered,
						IOrderIF_v1.OrderItemDTO.DeliveryStatuses.PartiallyDelivered => Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered,
						IOrderIF_v1.OrderItemDTO.DeliveryStatuses.Delivered => Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

				public static IOrderIF_v1.OrderItemDTO.DeliveryStatuses FromGrpc( Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses @this )
				{
					return @this switch
					{
						Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.NotDelivered => IOrderIF_v1.OrderItemDTO.DeliveryStatuses.NotDelivered,
						Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered => IOrderIF_v1.OrderItemDTO.DeliveryStatuses.PartiallyDelivered,
						Protos.OrderIF_v1.OrderItemDTO.Types.DeliveryStatuses.Delivered => IOrderIF_v1.OrderItemDTO.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

			}
			#endregion GrpcMapping
			public string productId { get; set; }
			public string productName { get; set; }
			public decimal quantity { get; set; }
			public decimal UnitPrice { get; set; }
			public string subTotalPrice { get; set; }
			public DeliveryStatuses deliveryStatus { get; set; }

			#region Clone & Copy 
			virtual public OrderItemDTO Clone()
			{
				OrderItemDTO clone = new();

				clone.productId = new string(productId.ToCharArray());
				clone.productName = new string(productName.ToCharArray());
				clone.quantity = quantity;
				clone.UnitPrice = UnitPrice;
				clone.subTotalPrice = new string(subTotalPrice.ToCharArray());
				clone.deliveryStatus = deliveryStatus;

				return clone;
			}
			#endregion Clone & Copy 

			#region GrpcMapping
			public static Protos.OrderIF_v1.OrderItemDTO ToGrpc( IOrderIF_v1.OrderItemDTO @this )
			{
				Protos.OrderIF_v1.OrderItemDTO result = new();

				result.ProductId = @this.productId;
				result.ProductName = @this.productName;
				result.Quantity = @this.quantity.ToString(CultureInfo.InvariantCulture);
				result.UnitPrice = @this.UnitPrice.ToString(CultureInfo.InvariantCulture);
				result.SubTotalPrice = @this.subTotalPrice;
				result.DeliveryStatus = IOrderIF_v1.OrderItemDTO.DeliveryStatusesMappings.ToGrpc( @this.deliveryStatus );

				return result;
			}
			public static IOrderIF_v1.OrderItemDTO FromGrpc( Protos.OrderIF_v1.OrderItemDTO @from )
			{
				IOrderIF_v1.OrderItemDTO result = new();

				result.productId = @from.ProductId;
				result.productName = @from.ProductName;
				result.quantity = decimal.Parse(@from.Quantity, CultureInfo.InvariantCulture);
				result.UnitPrice = decimal.Parse(@from.UnitPrice, CultureInfo.InvariantCulture);
				result.subTotalPrice = @from.SubTotalPrice;
				result.deliveryStatus = IOrderIF_v1.OrderItemDTO.DeliveryStatusesMappings.FromGrpc( @from.DeliveryStatus) ;

				return result;
			}
			#endregion GrpcMapping
		}

		public partial class OrderDTO
		{
			public partial class CustomerDataDTO
			{
				public string customerId { get; set; }
				public string customerName { get; set; }

				#region Clone & Copy 
				virtual public CustomerDataDTO Clone()
				{
					CustomerDataDTO clone = new();

					clone.customerId = new string(customerId.ToCharArray());
					clone.customerName = new string(customerName.ToCharArray());

					return clone;
				}
				#endregion Clone & Copy 

				#region GrpcMapping
				public static Protos.OrderIF_v1.OrderDTO.Types.CustomerDataDTO ToGrpc( IOrderIF_v1.OrderDTO.CustomerDataDTO @this )
				{
					Protos.OrderIF_v1.OrderDTO.Types.CustomerDataDTO result = new();

					result.CustomerId = @this.customerId;
					result.CustomerName = @this.customerName;

					return result;
				}
				public static IOrderIF_v1.OrderDTO.CustomerDataDTO FromGrpc( Protos.OrderIF_v1.OrderDTO.Types.CustomerDataDTO @from )
				{
					IOrderIF_v1.OrderDTO.CustomerDataDTO result = new();

					result.customerId = @from.CustomerId;
					result.customerName = @from.CustomerName;

					return result;
				}
				#endregion GrpcMapping
			}

			public string orderingDate { get; set; }
			public OrderStatuses orderStatus { get; set; }
			public decimal totalPrice { get; set; }
			public CustomerDataDTO customerData { get; set; }
			public List<OrderItemDTO> items { get; set; } = new();

			#region Clone & Copy 
			virtual public OrderDTO Clone()
			{
				OrderDTO clone = new();

				clone.orderingDate = new string(orderingDate.ToCharArray());
				clone.orderStatus = orderStatus;
				clone.totalPrice = totalPrice;
				clone.customerData = customerData?.Clone();
				clone.items.AddRange( items.Select( v => v.Clone() ));

				return clone;
			}
			#endregion Clone & Copy 

			#region GrpcMapping
			public static Protos.OrderIF_v1.OrderDTO ToGrpc( IOrderIF_v1.OrderDTO @this )
			{
				Protos.OrderIF_v1.OrderDTO result = new();

				result.OrderingDate = @this.orderingDate;
				result.OrderStatus = IOrderIF_v1.OrderStatusesMappings.ToGrpc( @this.orderStatus );
				result.TotalPrice = @this.totalPrice.ToString(CultureInfo.InvariantCulture);
				result.CustomerData = @this.customerData != null ? IOrderIF_v1.OrderDTO.CustomerDataDTO.ToGrpc( @this.customerData ) : null;
				result.Items.AddRange( @this.items.Select( v => IOrderIF_v1.OrderItemDTO.ToGrpc( v ) ));

				return result;
			}
			public static IOrderIF_v1.OrderDTO FromGrpc( Protos.OrderIF_v1.OrderDTO @from )
			{
				IOrderIF_v1.OrderDTO result = new();

				result.orderingDate = @from.OrderingDate;
				result.orderStatus = IOrderIF_v1.OrderStatusesMappings.FromGrpc( @from.OrderStatus) ;
				result.totalPrice = decimal.Parse(@from.TotalPrice, CultureInfo.InvariantCulture);
				result.customerData = @from.CustomerData != null ? IOrderIF_v1.OrderDTO.CustomerDataDTO.FromGrpc( @from.CustomerData ) : null;
				result.items.AddRange( @from.Items.Select( v => IOrderIF_v1.OrderItemDTO.FromGrpc(v) ));

				return result;
			}
			#endregion GrpcMapping
		}

	}
}
