
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist.Net;
using PolyPersist.Net.Core;
using ServiceKit.Net;

namespace Sales.OrderManagement
{

	public interface IOrderIF_v1
	{
		public Response<Order.OrderHeader> getOrder( CallingContext ctx, string orderId);

		public Response<Order.OrderHeader> placeOrder( CallingContext ctx, Order.OrderHeader order);

	}
}
