// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Google.Protobuf.Collections;
using PolyPersist;
using PolyPersist.Net.Common;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Globalization;

namespace Sales.OrderManagement
{
	/// The second version lives next to the first on purpose: this is how a published interface is
	/// carried forward without breaking the callers still on v1.
	public partial interface IOrderIF_v2
	{
		/// <return>IOrderIF_v2.OrderDTO</return>
		public Task<Response<IOrderIF_v2.OrderDTO>> getOrder(CallingContext ctx, string orderId);

		/// <return>IOrderIF_v2.OrderDTO</return>
		public Task<Response<IOrderIF_v2.OrderDTO>> placeOrder(CallingContext ctx, OrderDTO order);

		public Task<Response> justOrder(CallingContext ctx, string orderId);


		public partial class OrderPlaced_v2 : IEquatable<OrderPlaced_v2>
		{
			public string orderId { get; set; }
			public string customerId { get; set; }

			#region Clone 
			public virtual OrderPlaced_v2 Clone()
			{
				OrderPlaced_v2 clone = new();

				clone.orderId = new string(orderId.ToCharArray());
				clone.customerId = new string(customerId.ToCharArray());

				return clone;
			}
			#endregion Clone 

			#region Equals & HashCode 
			public bool Equals( OrderPlaced_v2 other )
			{
				if (other is null) return false;

				if(orderId != other.orderId) return false;
				if(customerId != other.customerId) return false;

				return true;
			}

			public override bool Equals(object obj) => Equals(obj as OrderPlaced_v2);

			public override int GetHashCode()
			{
				var hash = new HashCode();
				hash.Add(orderId);
				hash.Add(customerId);

				return hash.ToHashCode();
			}
			#endregion Equals & HashCode 
		}

		public enum OrderStatuses
		{
			Draft,
			Released,
			Finished,
			Canceled,
		}
		#region GrpcMapping
		public static class OrderStatusesMappings
		{
			public static Protos.OrderIF_v2.OrderStatuses ToGrpc( IOrderIF_v2.OrderStatuses @this )
			{
				return @this switch
				{
					IOrderIF_v2.OrderStatuses.Draft => Protos.OrderIF_v2.OrderStatuses.Draft,
					IOrderIF_v2.OrderStatuses.Released => Protos.OrderIF_v2.OrderStatuses.Released,
					IOrderIF_v2.OrderStatuses.Finished => Protos.OrderIF_v2.OrderStatuses.Finished,
					IOrderIF_v2.OrderStatuses.Canceled => Protos.OrderIF_v2.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

			public static IOrderIF_v2.OrderStatuses FromGrpc( Protos.OrderIF_v2.OrderStatuses @this )
			{
				return @this switch
				{
					Protos.OrderIF_v2.OrderStatuses.Draft => IOrderIF_v2.OrderStatuses.Draft,
					Protos.OrderIF_v2.OrderStatuses.Released => IOrderIF_v2.OrderStatuses.Released,
					Protos.OrderIF_v2.OrderStatuses.Finished => IOrderIF_v2.OrderStatuses.Finished,
					Protos.OrderIF_v2.OrderStatuses.Canceled => IOrderIF_v2.OrderStatuses.Canceled,
					_ => throw new NotImplementedException(), 
				};
			}

		}
		#endregion GrpcMapping
		public partial class OrderItemDTO : IEquatable<OrderItemDTO>, IValidable
		{
			public enum DeliveryStatuses
			{
				NotDelivered,
				PartiallyDelivered,
				Delivered,
			}
			#region GrpcMapping
			public static class DeliveryStatusesMappings
			{
				public static Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses ToGrpc( IOrderIF_v2.OrderItemDTO.DeliveryStatuses @this )
				{
					return @this switch
					{
						IOrderIF_v2.OrderItemDTO.DeliveryStatuses.NotDelivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.NotDelivered,
						IOrderIF_v2.OrderItemDTO.DeliveryStatuses.PartiallyDelivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered,
						IOrderIF_v2.OrderItemDTO.DeliveryStatuses.Delivered => Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

				public static IOrderIF_v2.OrderItemDTO.DeliveryStatuses FromGrpc( Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses @this )
				{
					return @this switch
					{
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.NotDelivered => IOrderIF_v2.OrderItemDTO.DeliveryStatuses.NotDelivered,
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.PartiallyDelivered => IOrderIF_v2.OrderItemDTO.DeliveryStatuses.PartiallyDelivered,
						Protos.OrderIF_v2.OrderItemDTO.Types.DeliveryStatuses.Delivered => IOrderIF_v2.OrderItemDTO.DeliveryStatuses.Delivered,
						_ => throw new NotImplementedException(), 
					};
				}

			}
			#endregion GrpcMapping
			public string productId { get; set; }
			public string productName { get; set; }
			public decimal quantity { get; set; }
			public decimal unitPrice { get; set; }
			public decimal subTotalPrice { get; set; }
			public IOrderIF_v2.OrderItemDTO.DeliveryStatuses deliveryStatus { get; set; }

			#region Clone 
			public virtual OrderItemDTO Clone()
			{
				OrderItemDTO clone = new();

				clone.productId = new string(productId.ToCharArray());
				clone.productName = new string(productName.ToCharArray());
				clone.quantity = quantity;
				clone.unitPrice = unitPrice;
				clone.subTotalPrice = subTotalPrice;
				clone.deliveryStatus = deliveryStatus;

				return clone;
			}
			#endregion Clone 

			#region Equals & HashCode 
			public bool Equals( OrderItemDTO other )
			{
				if (other is null) return false;

				if(productId != other.productId) return false;
				if(productName != other.productName) return false;
				if(quantity != other.quantity) return false;
				if(unitPrice != other.unitPrice) return false;
				if(subTotalPrice != other.subTotalPrice) return false;
				if(deliveryStatus != other.deliveryStatus) return false;

				return true;
			}

			public override bool Equals(object obj) => Equals(obj as OrderItemDTO);

			public override int GetHashCode()
			{
				var hash = new HashCode();
				hash.Add(productId);
				hash.Add(productName);
				hash.Add(quantity);
				hash.Add(unitPrice);
				hash.Add(subTotalPrice);
				hash.Add(deliveryStatus);

				return hash.ToHashCode();
			}
			#endregion Equals & HashCode 

			#region Validation
			public virtual bool Validate( IList<IValidationError> errors )
			{
				int before = errors.Count;
				ValidateInto( errors, string.Empty );
				return errors.Count == before;
			}

			public virtual void ValidateInto( IList<IValidationError> errors, string pathPrefix )
			{
				if (quantity <= 0)
					errors.Add( new ValidationError { TypeOfEntity = "OrderItemDTO", MemberOfEntity = "quantity", Path = pathPrefix + "quantity", ErrorText = "quantity must satisfy: value > 0" } );

				if (unitPrice < 0)
					errors.Add( new ValidationError { TypeOfEntity = "OrderItemDTO", MemberOfEntity = "unitPrice", Path = pathPrefix + "unitPrice", ErrorText = "unitPrice must satisfy: value >= 0" } );
			}
			#endregion Validation

			#region GrpcMapping
			public static Protos.OrderIF_v2.OrderItemDTO ToGrpc( IOrderIF_v2.OrderItemDTO @this )
			{
				Protos.OrderIF_v2.OrderItemDTO result = new();

				result.ProductId = @this.productId;
				result.ProductName = @this.productName;
				result.Quantity = @this.quantity.ToString(CultureInfo.InvariantCulture);
				result.UnitPrice = @this.unitPrice.ToString(CultureInfo.InvariantCulture);
				result.SubTotalPrice = @this.subTotalPrice.ToString(CultureInfo.InvariantCulture);
				result.DeliveryStatus = IOrderIF_v2.OrderItemDTO.DeliveryStatusesMappings.ToGrpc( @this.deliveryStatus );

				return result;
			}
			public static IOrderIF_v2.OrderItemDTO FromGrpc( Protos.OrderIF_v2.OrderItemDTO @from )
			{
				IOrderIF_v2.OrderItemDTO result = new();

				result.productId = @from.ProductId;
				result.productName = @from.ProductName;
				result.quantity = decimal.Parse(@from.Quantity, CultureInfo.InvariantCulture);
				result.unitPrice = decimal.Parse(@from.UnitPrice, CultureInfo.InvariantCulture);
				result.subTotalPrice = decimal.Parse(@from.SubTotalPrice, CultureInfo.InvariantCulture);
				result.deliveryStatus = IOrderIF_v2.OrderItemDTO.DeliveryStatusesMappings.FromGrpc( @from.DeliveryStatus) ;

				return result;
			}
			#endregion GrpcMapping
		}

		public partial class OrderDTO : IEquatable<OrderDTO>, IValidable
		{
			public partial class CustomerDataDTO : IEquatable<CustomerDataDTO>
			{
				public string customerId { get; set; }
				public string customerName { get; set; }

				#region Clone 
				public virtual CustomerDataDTO Clone()
				{
					CustomerDataDTO clone = new();

					clone.customerId = new string(customerId.ToCharArray());
					clone.customerName = new string(customerName.ToCharArray());

					return clone;
				}
				#endregion Clone 

				#region Equals & HashCode 
				public bool Equals( CustomerDataDTO other )
				{
					if (other is null) return false;

					if(customerId != other.customerId) return false;
					if(customerName != other.customerName) return false;

					return true;
				}

				public override bool Equals(object obj) => Equals(obj as CustomerDataDTO);

				public override int GetHashCode()
				{
					var hash = new HashCode();
					hash.Add(customerId);
					hash.Add(customerName);

					return hash.ToHashCode();
				}
				#endregion Equals & HashCode 

				#region GrpcMapping
				public static Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO ToGrpc( IOrderIF_v2.OrderDTO.CustomerDataDTO @this )
				{
					Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO result = new();

					result.CustomerId = @this.customerId;
					result.CustomerName = @this.customerName;

					return result;
				}
				public static IOrderIF_v2.OrderDTO.CustomerDataDTO FromGrpc( Protos.OrderIF_v2.OrderDTO.Types.CustomerDataDTO @from )
				{
					IOrderIF_v2.OrderDTO.CustomerDataDTO result = new();

					result.customerId = @from.CustomerId;
					result.customerName = @from.CustomerName;

					return result;
				}
				#endregion GrpcMapping
			}

			public string id { get; set; }
			public string orderingDate { get; set; }
			public IOrderIF_v2.OrderStatuses orderStatus { get; set; }
			public decimal totalPrice { get; set; }
			public IOrderIF_v2.OrderDTO.CustomerDataDTO customerData { get; set; }
			public List<IOrderIF_v2.OrderItemDTO> items { get; set; } = new();
			/// v2 addition: where the parcel is going
			public string? shippingCity { get; set; }

			#region Clone 
			public virtual OrderDTO Clone()
			{
				OrderDTO clone = new();

				clone.orderingDate = new string(orderingDate.ToCharArray());
				clone.orderStatus = orderStatus;
				clone.totalPrice = totalPrice;

				// clone of customerData
				clone.customerData = customerData?.Clone();

				// clone of items
				clone.items.AddRange( items.Select( v => v.Clone() ));
				clone.shippingCity = new string(shippingCity.ToCharArray());

				return clone;
			}
			#endregion Clone 

			#region Equals & HashCode 
			public bool Equals( OrderDTO other )
			{
				if (other is null) return false;

				if(orderingDate != other.orderingDate) return false;
				if(orderStatus != other.orderStatus) return false;
				if(totalPrice != other.totalPrice) return false;

				// equals of customerData
				if(customerData == null && other.customerData != null ) return false;
				if(customerData != null && customerData.Equals(other.customerData) == false ) return false;

				// equals of items
				if(items.SequenceEqual(other.items) == false ) return false;
				if(shippingCity != other.shippingCity) return false;

				return true;
			}

			public override bool Equals(object obj) => Equals(obj as OrderDTO);

			public override int GetHashCode()
			{
				var hash = new HashCode();
				hash.Add(id);
				hash.Add(orderingDate);
				hash.Add(orderStatus);
				hash.Add(totalPrice);

				// hash of customerData
				if(customerData != null ) hash.Add(customerData);

				// hash of items
				foreach( var element_items in items)
					hash.Add(element_items);
				hash.Add(shippingCity);

				return hash.ToHashCode();
			}
			#endregion Equals & HashCode 

			#region Validation
			public virtual bool Validate( IList<IValidationError> errors )
			{
				int before = errors.Count;
				ValidateInto( errors, string.Empty );
				return errors.Count == before;
			}

			public virtual void ValidateInto( IList<IValidationError> errors, string pathPrefix )
			{
				if (items != null)
				{
					for (int index = 0; index < items.Count; index++)
						items[index]?.ValidateInto( errors, $"{pathPrefix}items[{index}]." );
				}
			}
			#endregion Validation

			#region GrpcMapping
			public static Protos.OrderIF_v2.OrderDTO ToGrpc( IOrderIF_v2.OrderDTO @this )
			{
				Protos.OrderIF_v2.OrderDTO result = new();

				result.Id = @this.id;
				result.OrderingDate = @this.orderingDate;
				result.OrderStatus = IOrderIF_v2.OrderStatusesMappings.ToGrpc( @this.orderStatus );
				result.TotalPrice = @this.totalPrice.ToString(CultureInfo.InvariantCulture);
				result.CustomerData = @this.customerData != null ? IOrderIF_v2.OrderDTO.CustomerDataDTO.ToGrpc( @this.customerData ) : null;
				result.Items.AddRange( @this.items.Select( v => IOrderIF_v2.OrderItemDTO.ToGrpc( v ) ));
				result.ShippingCity = @this.shippingCity;

				return result;
			}
			public static IOrderIF_v2.OrderDTO FromGrpc( Protos.OrderIF_v2.OrderDTO @from )
			{
				IOrderIF_v2.OrderDTO result = new();

				result.id = @from.Id;
				result.orderingDate = @from.OrderingDate;
				result.orderStatus = IOrderIF_v2.OrderStatusesMappings.FromGrpc( @from.OrderStatus) ;
				result.totalPrice = decimal.Parse(@from.TotalPrice, CultureInfo.InvariantCulture);
				result.customerData = @from.CustomerData != null ? IOrderIF_v2.OrderDTO.CustomerDataDTO.FromGrpc( @from.CustomerData ) : null;
				result.items.AddRange( @from.Items.Select( v => IOrderIF_v2.OrderItemDTO.FromGrpc(v) ));
				result.shippingCity = @from.ShippingCity;

				return result;
			}
			#endregion GrpcMapping
		}

	}
}
