// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace Sales.OrderManagement
{
	/// <summary>
	/// Translates this context's internal facts into what 'OrderIF' publishes.
	/// The bodies are yours: a published contract is a deliberate restatement of an internal
	/// fact, not a copy of it, and only you know what the outside world is entitled to see.
	/// </summary>
	public static partial class OrderIF_v2Translations
	{
		/// <summary>'OrderPlaced' as 'OrderIF' publishes it.</summary>
		public static partial IOrderIF_v2.OrderPlaced_v2 ToOrderPlaced_v2( Order.OrderPlaced @event );

	}
}
