
// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

using Sales.OrderManagement;
using ServiceKit.Net;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;

namespace Sales.OrderManagement
{
	public class OrderIF_v2_RestClient : IOrderIF_v2 
	{
		private readonly HttpClient _httpClient;

		OrderIF_v2_RestClient( string serverAddress )
		{
			_httpClient = new HttpClient();
			_httpClient.BaseAddress = new Uri( serverAddress );
			_httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.getOrder(CallingContext ctx, string orderId)
		{
			try
			{
				_httpClient.DefaultRequestHeaders.Remove("x-request-id");
				_httpClient.DefaultRequestHeaders.Add("x-request-id", Guid.NewGuid().ToString());

				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, WebUtility.UrlEncode( $"/sales/ordermanagement/orderif/v2/getorder/{orderId}" ) );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "getOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v2.OrderDTO>();
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var error = await response.Content.ReadFromJsonAsync<Error>();
					return Response<IOrderIF_v2.OrderDTO>.Failure( error );
				}
				else
				{
					return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
						Status = response.StatusCode.FromHttp(),
						MessageText = "Not handled reponse in GRPC client when calling 'OrderIF_v2_getOrder'",
					} );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
					Status = ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
					Status = Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.placeOrder(CallingContext ctx, IOrderIF_v2.OrderDTO order)
		{
			try
			{
				_httpClient.DefaultRequestHeaders.Remove("x-request-id");
				_httpClient.DefaultRequestHeaders.Add("x-request-id", Guid.NewGuid().ToString());

				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, WebUtility.UrlEncode( $"/sales/ordermanagement/orderif/v2/placeorder" ) );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "placeOrder" );

				// build content
				request.Content = new StringContent( JsonSerializer.Serialize<IOrderIF_v2.OrderDTO>( order ));

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v2.OrderDTO>();
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var error = await response.Content.ReadFromJsonAsync<Error>();
					return Response<IOrderIF_v2.OrderDTO>.Failure( error );
				}
				else
				{
					return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
						Status = response.StatusCode.FromHttp(),
						MessageText = "Not handled reponse in GRPC client when calling 'OrderIF_v2_placeOrder'",
					} );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
					Status = ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( new ServiceKit.Net.Error() {
					Status = Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response> IOrderIF_v2.justOrder(CallingContext ctx, string orderId)
		{
			try
			{
				_httpClient.DefaultRequestHeaders.Remove("x-request-id");
				_httpClient.DefaultRequestHeaders.Add("x-request-id", Guid.NewGuid().ToString());

				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, WebUtility.UrlEncode( $"/sales/ordermanagement/orderif/v2/justorder/{orderId}" ) );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "justOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					return Response.Success();
				}
				else if( response.Content != null )
				{
					var error = await response.Content.ReadFromJsonAsync<Error>();
					return Response.Failure( error );
				}
				else
				{
					return Response.Failure( new ServiceKit.Net.Error() {
						Status = response.StatusCode.FromHttp(),
						MessageText = "Not handled reponse in GRPC client when calling 'OrderIF_v2_justOrder'",
					} );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response.Failure( new ServiceKit.Net.Error() {
					Status = ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response.Failure( new ServiceKit.Net.Error() {
					Status = Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

	}
}
