// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Grpc.Net.Client;
using Sales.OrderManagement;
using Sales.OrderManagement.Protos.OrderIF_v2;
using ServiceKit.Net;
using System.Linq;

namespace Sales.OrderManagement
{
	/// The second version lives next to the first on purpose: this is how a published interface is
	/// carried forward without breaking the callers still on v1.
	public class OrderIF_v2_GrpcClient : IOrderIF_v2 
	{
		private readonly GrpcChannel _channel;
		private readonly OrderIF_v2.OrderIF_v2Client _client;

		OrderIF_v2_GrpcClient( string serverAddress )
		{
			_channel = GrpcChannel.ForAddress(serverAddress);
			_client = new OrderIF_v2.OrderIF_v2Client(_channel);
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.getOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// fill grpc request
				var request = new OrderIF_v2_getOrderRequest();
				request.OrderId = orderId;

				// calling grpc client
				var grpc_response = await _client.getOrderAsync( request, new CallOptions(ctx.ToGrpcMetadata( "Sales.OrderManagementOrderIF_v2", "getOrder" ))).ResponseAsync;

				// fill response
				if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
					return Response<IOrderIF_v2.OrderDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

				if( grpc_response.ResultCase == OrderIF_v2_getOrderResponse.ResultOneofCase.Value )
				{
					IOrderIF_v2.OrderDTO value;
					value = grpc_response.Value != null ? IOrderIF_v2.OrderDTO.FromGrpc( grpc_response.Value ) : null;
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}

				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'OrderIF_v2_getOrder'" );
			}
			catch (RpcException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.placeOrder(CallingContext ctx, IOrderIF_v2.OrderDTO order)
		{
			try
			{
				// fill grpc request
				var request = new OrderIF_v2_placeOrderRequest();
				request.Order = order != null ? IOrderIF_v2.OrderDTO.ToGrpc( order ) : null;

				// calling grpc client
				var grpc_response = await _client.placeOrderAsync( request, new CallOptions(ctx.ToGrpcMetadata( "Sales.OrderManagementOrderIF_v2", "placeOrder" ))).ResponseAsync;

				// fill response
				if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
					return Response<IOrderIF_v2.OrderDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

				if( grpc_response.ResultCase == OrderIF_v2_placeOrderResponse.ResultOneofCase.Value )
				{
					IOrderIF_v2.OrderDTO value;
					value = grpc_response.Value != null ? IOrderIF_v2.OrderDTO.FromGrpc( grpc_response.Value ) : null;
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}

				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'OrderIF_v2_placeOrder'" );
			}
			catch (RpcException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response> IOrderIF_v2.justOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// fill grpc request
				var request = new OrderIF_v2_justOrderRequest();
				request.OrderId = orderId;

				// calling grpc client
				var grpc_response = await _client.justOrderAsync( request, new CallOptions(ctx.ToGrpcMetadata( "Sales.OrderManagementOrderIF_v2", "justOrder" ))).ResponseAsync;

				// fill response
				if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
					return Response.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

				return Response.Success();
			}
			catch (RpcException ex)
			{
				return Response.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}


		private static ServiceKit.Net.Error[] _FromGrpcErrors( IEnumerable<ServiceKit.Protos.Error> errors )
		{
			return errors.Select( error => new ServiceKit.Net.Error() {
				Path = error.Path,
				MessageText = error.MessageText,
				AdditionalInformation = error.AdditionalInformation,
			} ).ToArray();
		}
	}
}
