// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Sales.OrderManagement
{
	/// The second version lives next to the first on purpose: this is how a published interface is
	/// carried forward without breaking the callers still on v1.
	public class OrderIF_v2_RestClient : IOrderIF_v2 
	{
		/// <summary>
		/// The service this client calls. Its address is configuration:
		/// Services:Sales.OrderManagement:BaseAddress (and :GrpcAddress when cleartext needs a second port).
		/// </summary>
		public const string ServiceName = "Sales.OrderManagement";

		private readonly HttpClient _httpClient;
		// the same options the host is configured with: web defaults, and enums by name
		private static readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions( JsonSerializerDefaults.Web )
		{
			Converters = { new JsonStringEnumConverter() },
		};

		public OrderIF_v2_RestClient( IServiceClientFactory clients )
		{
			// From the factory, not from 'new HttpClient()'. A hand-made one holds its connections
			// open and never notices DNS changing - which is the kind of bug that works perfectly
			// until there is traffic. The factory's client also carries the house retry policy.
			_httpClient = clients.CreateHttpClient( ServiceName );
			_httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.getOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, $"/sales/ordermanagement/orderif/v2/getorder/{Uri.EscapeDataString(orderId)}" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "getOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v2.OrderDTO>( _jsonOptions );
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response<IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response<IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_getOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v2.OrderDTO>> IOrderIF_v2.placeOrder(CallingContext ctx, IOrderIF_v2.OrderDTO order)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v2/placeorder" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "placeOrder" );

				// build content
				request.Content = new StringContent( JsonSerializer.Serialize<IOrderIF_v2.OrderDTO>( order, _jsonOptions ), Encoding.UTF8, "application/json" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v2.OrderDTO>( _jsonOptions );
					return Response<IOrderIF_v2.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response<IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response<IOrderIF_v2.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_placeOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v2.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response> IOrderIF_v2.justOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v2/justorder/{Uri.EscapeDataString(orderId)}" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v2", "justOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					return Response.Success();
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v2_justOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

	}
}
