// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;
using Sales.OrderManagement;
using ServiceKit.Net;
using System.Globalization;
using System.Net;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Sales.OrderManagement
{
	/// The published surface of orders: DTOs only, no domain type ever reaches the wire.
	public class OrderIF_v1_RestClient : IOrderIF_v1 
	{
		/// <summary>
		/// The service this client calls. Its address is configuration:
		/// Services:Sales.OrderManagement:BaseAddress (and :GrpcAddress when cleartext needs a second port).
		/// </summary>
		public const string ServiceName = "Sales.OrderManagement";

		private readonly HttpClient _httpClient;
		// the same options the host is configured with: web defaults, and enums by name
		private static readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions( JsonSerializerDefaults.Web )
		{
			Converters = { new JsonStringEnumConverter() },
		};

		public OrderIF_v1_RestClient( IServiceClientFactory clients )
		{
			// From the factory, not from 'new HttpClient()'. A hand-made one holds its connections
			// open and never notices DNS changing - which is the kind of bug that works perfectly
			// until there is traffic. The factory's client also carries the house retry policy.
			_httpClient = clients.CreateHttpClient( ServiceName );
			_httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v1.OrderDTO>> IOrderIF_v1.getOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Get, $"/sales/ordermanagement/orderif/v1/getorder/{Uri.EscapeDataString(orderId)}" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v1", "getOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v1.OrderDTO>( _jsonOptions );
					if (value is null)
						return Response<IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, "The server answered 'getOrder' with a success status and an empty body." );

					return Response<IOrderIF_v1.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response<IOrderIF_v1.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response<IOrderIF_v1.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v1_getOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v1.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v1.OrderDTO>> IOrderIF_v1.placeOrder(CallingContext ctx, IOrderIF_v1.OrderDTO order)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v1/placeorder" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v1", "placeOrder" );

				// build content
				request.Content = new StringContent( JsonSerializer.Serialize<IOrderIF_v1.OrderDTO>( order, _jsonOptions ), Encoding.UTF8, "application/json" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v1.OrderDTO>( _jsonOptions );
					if (value is null)
						return Response<IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, "The server answered 'placeOrder' with a success status and an empty body." );

					return Response<IOrderIF_v1.OrderDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response<IOrderIF_v1.OrderDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response<IOrderIF_v1.OrderDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v1_placeOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v1.OrderDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v1.OrderDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<IOrderIF_v1.OrderItemDTO>> IOrderIF_v1.setPrice(CallingContext ctx, IOrderIF_v1.OrderItemDTO orderItem, decimal price)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v1/setprice?price={Uri.EscapeDataString(price.ToString(CultureInfo.InvariantCulture))}" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v1", "setPrice" );

				// build content
				request.Content = new StringContent( JsonSerializer.Serialize<IOrderIF_v1.OrderItemDTO>( orderItem, _jsonOptions ), Encoding.UTF8, "application/json" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					var value = await response.Content.ReadFromJsonAsync<IOrderIF_v1.OrderItemDTO>( _jsonOptions );
					if (value is null)
						return Response<IOrderIF_v1.OrderItemDTO>.Failure( Statuses.InternalError, "The server answered 'setPrice' with a success status and an empty body." );

					return Response<IOrderIF_v1.OrderItemDTO>.Success( value );
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response<IOrderIF_v1.OrderItemDTO>.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response<IOrderIF_v1.OrderItemDTO>.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v1_setPrice'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response<IOrderIF_v1.OrderItemDTO>.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<IOrderIF_v1.OrderItemDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response> IOrderIF_v1.justOrder(CallingContext ctx, string orderId)
		{
			try
			{
				// build request
				HttpRequestMessage request = new HttpRequestMessage( HttpMethod.Post, $"/sales/ordermanagement/orderif/v1/justorder/{Uri.EscapeDataString(orderId)}" );
				ctx.FillHttpRequest( request, "SalesOrderManagementOrderIF_v1", "justOrder" );

				// call http client 
				HttpResponseMessage response = await _httpClient.SendAsync( request );

				if (response.IsSuccessStatusCode)
				{
					return Response.Success();
				}
				else if( response.Content != null )
				{
					var errors = await response.Content.ReadFromJsonAsync<List<ServiceKit.Net.Error>>( _jsonOptions );
					return Response.Failure( response.StatusCode.FromHttp(), errors?.ToArray() ?? Array.Empty<ServiceKit.Net.Error>() );
				}
				else
				{
					return Response.Failure( response.StatusCode.FromHttp(), "Not handled reponse in REST client when calling 'OrderIF_v1_justOrder'" );
				}
			}
			catch (HttpRequestException ex)
			{
				return Response.Failure( ex.StatusCode.HasValue ? ex.StatusCode.Value.FromHttp() : Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

	}
}
