
// <auto-generated>
// This code was generated by d3i.interpreter
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

import { BFFRestClient } from "../../../api/BFFRestClient";
import { AxiosError } from 'axios';
import * as CustomerIF_v1 from "../../../types/CustomerManagement/Customers/CustomerIF_v1";

const rest = BFFRestClient.getInstance()

export const CustomerIF = {
	V1: {
		async getCustomer(customerId: string): Promise<CustomerIF_v1.CustomerDTO> {
			try {
				const extraHeaders = rest.getRequestHeaders("CustomerManagement.Customers.getCustomer");

				const response = await rest.axios.get<CustomerIF_v1.CustomerDTO>(
					`/customermanagement/customers/customerif/v1/getcustomer/${encodeURIComponent(customerId)}`,
					{ headers: extraHeaders }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "getCustomer");
			}
		}
		,
		async registerCustomer(name: string, email: string): Promise<CustomerIF_v1.CustomerDTO> {
			try {
				const extraHeaders = rest.getRequestHeaders("CustomerManagement.Customers.registerCustomer");

				const response = await rest.axios.post<CustomerIF_v1.CustomerDTO>(
					`/customermanagement/customers/customerif/v1/registercustomer/${encodeURIComponent(name)}/${encodeURIComponent(email)}`,
					{ headers: extraHeaders }
				);

				return response.data;
			}
			catch (error: unknown) {
				throw rest.mapApiError(error as AxiosError, "registerCustomer");
			}
		}
		,
		}
}
