// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using CustomerManagement.Customers.Protos.CustomerIF_v1;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using ServiceKit.Net;
using System.Linq;

namespace CustomerManagement.Customers
{
	public class CustomerIF_v1_GrpcClient : ICustomerIF_v1 
	{
		/// <summary>
		/// The service this client calls. Its address is configuration:
		/// Services:CustomerManagement.Customers:BaseAddress (and :GrpcAddress when cleartext needs a second port).
		/// </summary>
		public const string ServiceName = "CustomerManagement.Customers";

		private readonly CustomerIF_v1.CustomerIF_v1Client _client;

		public CustomerIF_v1_GrpcClient( IServiceClientFactory clients )
		{
			// The channel comes from the factory and is NOT held or disposed here. A channel owns the
			// connection, the HTTP/2 session and the load balancing state, so one per call site is a
			// connection storm; the factory keeps one per address and everybody shares it.
			_client = new CustomerIF_v1.CustomerIF_v1Client( clients.GetChannel( ServiceName ) );
		}

		/// <inheritdoc />
		async Task<Response<ICustomerIF_v1.CustomerDTO>> ICustomerIF_v1.getCustomer(CallingContext ctx, string customerId)
		{
			try
			{
				// fill grpc request
				var request = new CustomerIF_v1_getCustomerRequest();
				request.CustomerId = customerId ?? string.Empty;

				// calling grpc client
				var grpc_response = await _client.getCustomerAsync( request, new CallOptions(ctx.ToGrpcMetadata( "CustomerManagement.CustomersCustomerIF_v1", "getCustomer" ))).ResponseAsync;

				// fill response
				if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
					return Response<ICustomerIF_v1.CustomerDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

				if( grpc_response.ResultCase == CustomerIF_v1_getCustomerResponse.ResultOneofCase.Value )
				{
					ICustomerIF_v1.CustomerDTO value;
					value = grpc_response.Value != null ? ICustomerIF_v1.CustomerDTO.FromGrpc( grpc_response.Value ) : null;
					return Response<ICustomerIF_v1.CustomerDTO>.Success( value );
				}

				return Response<ICustomerIF_v1.CustomerDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'CustomerIF_v1_getCustomer'" );
			}
			catch (RpcException ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<ICustomerIF_v1.CustomerDTO>> ICustomerIF_v1.registerCustomer(CallingContext ctx, string name, string email)
		{
			try
			{
				// fill grpc request
				var request = new CustomerIF_v1_registerCustomerRequest();
				request.Name = name ?? string.Empty;
				request.Email = email ?? string.Empty;

				// calling grpc client
				var grpc_response = await _client.registerCustomerAsync( request, new CallOptions(ctx.ToGrpcMetadata( "CustomerManagement.CustomersCustomerIF_v1", "registerCustomer" ))).ResponseAsync;

				// fill response
				if( grpc_response.Status != ServiceKit.Protos.Statuses.Ok )
					return Response<ICustomerIF_v1.CustomerDTO>.Failure( grpc_response.Status.FromGrpc(), _FromGrpcErrors( grpc_response.Errors ) );

				if( grpc_response.ResultCase == CustomerIF_v1_registerCustomerResponse.ResultOneofCase.Value )
				{
					ICustomerIF_v1.CustomerDTO value;
					value = grpc_response.Value != null ? ICustomerIF_v1.CustomerDTO.FromGrpc( grpc_response.Value ) : null;
					return Response<ICustomerIF_v1.CustomerDTO>.Success( value );
				}

				return Response<ICustomerIF_v1.CustomerDTO>.Failure( Statuses.NotImplemented, "Not handled reponse in GRPC client when calling 'CustomerIF_v1_registerCustomer'" );
			}
			catch (RpcException ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( ex.StatusCode.FromGrpc(), new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( Statuses.InternalError, new ServiceKit.Net.Error() {
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}


		private static ServiceKit.Net.Error[] _FromGrpcErrors( IEnumerable<ServiceKit.Protos.Error> errors )
		{
			return errors.Select( error => new ServiceKit.Net.Error() {
				Path = error.Path,
				MessageText = error.MessageText,
				AdditionalInformation = error.AdditionalInformation,
			} ).ToArray();
		}
	}
}
