// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using CustomerManagement.Customers.Protos.CustomerIF_v1;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Grpc.Net.Client;
using ServiceKit.Net;

namespace CustomerManagement.Customers
{
	public class CustomerIF_v1_GrpcClient : ICustomerIF_v1 
	{
		private readonly GrpcChannel _channel;
		private readonly CustomerIF_v1.CustomerIF_v1Client _client;

		CustomerIF_v1_GrpcClient( string serverAddress )
		{
			_channel = GrpcChannel.ForAddress(serverAddress);
			_client = new CustomerIF_v1.CustomerIF_v1Client(_channel);
		}

		/// <inheritdoc />
		async Task<Response<ICustomerIF_v1.CustomerDTO>> ICustomerIF_v1.getCustomer(CallingContext ctx, string customerId)
		{
			try
			{
				// fill grpc request
				var request = new CustomerIF_v1_getCustomerRequest();
				request.CustomerId = customerId;

				// calling grpc client
				var grpc_response = await _client.getCustomerAsync( request, new CallOptions(ctx.ToGrpcMetadata( "CustomerManagement.CustomersCustomerIF_v1", "getCustomer" ))).ResponseAsync;

				// fill response
				switch( grpc_response.ResultCase )
				{
					case CustomerIF_v1_getCustomerResponse.ResultOneofCase.Value:
						ICustomerIF_v1.CustomerDTO value;
						value = grpc_response.Value != null ? ICustomerIF_v1.CustomerDTO.FromGrpc( grpc_response.Value ) : null;
						return Response<ICustomerIF_v1.CustomerDTO>.Success( value );

					case CustomerIF_v1_getCustomerResponse.ResultOneofCase.Error:
						return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = grpc_response.Error.Status.FromGrpc(),
							MessageText = grpc_response.Error.MessageText,
							AdditionalInformation = grpc_response.Error.AdditionalInformation,
						} );

					case CustomerIF_v1_getCustomerResponse.ResultOneofCase.None:
					default:
						return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = grpc_response.Error.Status.FromGrpc(),
							MessageText = "Not handled reponse in GRPC client when calling 'CustomerIF_v1_getCustomer'",
						} );
				}
			}
			catch (RpcException ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
					Status = ex.StatusCode.FromGrpc(),
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
					Status = Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

		/// <inheritdoc />
		async Task<Response<ICustomerIF_v1.CustomerDTO>> ICustomerIF_v1.registerCustomer(CallingContext ctx, string name, string email)
		{
			try
			{
				// fill grpc request
				var request = new CustomerIF_v1_registerCustomerRequest();
				request.Name = name;
				request.Email = email;

				// calling grpc client
				var grpc_response = await _client.registerCustomerAsync( request, new CallOptions(ctx.ToGrpcMetadata( "CustomerManagement.CustomersCustomerIF_v1", "registerCustomer" ))).ResponseAsync;

				// fill response
				switch( grpc_response.ResultCase )
				{
					case CustomerIF_v1_registerCustomerResponse.ResultOneofCase.Value:
						ICustomerIF_v1.CustomerDTO value;
						value = grpc_response.Value != null ? ICustomerIF_v1.CustomerDTO.FromGrpc( grpc_response.Value ) : null;
						return Response<ICustomerIF_v1.CustomerDTO>.Success( value );

					case CustomerIF_v1_registerCustomerResponse.ResultOneofCase.Error:
						return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = grpc_response.Error.Status.FromGrpc(),
							MessageText = grpc_response.Error.MessageText,
							AdditionalInformation = grpc_response.Error.AdditionalInformation,
						} );

					case CustomerIF_v1_registerCustomerResponse.ResultOneofCase.None:
					default:
						return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
							Status = grpc_response.Error.Status.FromGrpc(),
							MessageText = "Not handled reponse in GRPC client when calling 'CustomerIF_v1_registerCustomer'",
						} );
				}
			}
			catch (RpcException ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
					Status = ex.StatusCode.FromGrpc(),
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
			catch (Exception ex)
			{
				return Response<ICustomerIF_v1.CustomerDTO>.Failure( new ServiceKit.Net.Error() {
					Status = Statuses.InternalError,
					MessageText = ex.Message,
					AdditionalInformation = ex.ToString(),
				} );
			}
		}

	}
}
