// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Microsoft.Extensions.Logging;
using Sales.OrderManagement;
using Sales.OrderManagement.Protos.OrderIF_v2;
using Serilog.Context;
using ServiceKit.Net;
using System.Linq;

namespace Sales.OrderManagement
{
	/// The second version lives next to the first on purpose: this is how a published interface is
	/// carried forward without breaking the callers still on v1.
	[AutoRegisterGrpc]
	public class OrderIF_v2_GrpcController : Sales.OrderManagement.Protos.OrderIF_v2.OrderIF_v2.OrderIF_v2Base 
	{
		private readonly ILogger<OrderIF_v2_GrpcController> _logger;
		private readonly IOrderIF_v2 _service;

		public OrderIF_v2_GrpcController( ILogger<OrderIF_v2_GrpcController> logger, IOrderIF_v2 service )
		{
			_logger = logger; 
			_service = service; 
		}

		private static (Statuses Status, IList<ServiceKit.Net.Error> Errors) _MapFailure( Exception ex )
		{
			// a broken field is the caller's to fix, and every rule that failed is worth reporting
			if( ex is PolyPersist.Net.Common.ValidationExeption validationExeption )
				return (Statuses.BadRequest, validationExeption.ValidationErrors.Select( validationError => new ServiceKit.Net.Error() {
					Path = validationError.Path,
					MessageText = validationError.ErrorText,
					AdditionalInformation = $"{validationError.TypeOfEntity}.{validationError.MemberOfEntity}",
				} ).ToList<ServiceKit.Net.Error>());

			if( ex is PolyPersist.Net.Common.NotFoundException )
				return (Statuses.NotFound, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			if( ex is PolyPersist.Net.Common.DuplicateKeyException
				|| ex is PolyPersist.Net.Common.ConcurrencyConflictException
				|| ex is PolyPersist.Net.Common.InvalidRequestException )
				return (Statuses.BadRequest, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			// anything else really is ours: the caller can do nothing about it, so say so plainly
			return (Statuses.InternalError, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message, AdditionalInformation = ex.ToString() } });
		}

		public override async Task<OrderIF_v2_getOrderResponse> getOrder( OrderIF_v2_getOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.getOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string orderId;
					orderId = request.OrderId;

					// calling the service function itself
					var response = await _service.getOrder( ctx , orderId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new OrderIF_v2_getOrderResponse() { Status = ServiceKit.Protos.Statuses.Ok };
							result.Value = response.Value != null ? IOrderIF_v2.OrderDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return _GrpcFailure_getOrder( Statuses.NotImplemented, new [] { new ServiceKit.Net.Error() { MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF_v2.getOrder'" } } );
						}
					}
					else
					{
						return _GrpcFailure_getOrder( response.Status, response.Errors );
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return _GrpcFailure_getOrder( failure.Status, failure.Errors );
				}
			}
		}

		private static OrderIF_v2_getOrderResponse _GrpcFailure_getOrder( Statuses status, IEnumerable<ServiceKit.Net.Error> errors )
		{
			var failure = new OrderIF_v2_getOrderResponse() { Status = status.ToGrpc() };
			foreach( var error in errors )
				failure.Errors.Add( new ServiceKit.Protos.Error() {
					Path = error.Path ?? string.Empty,
					MessageText = error.MessageText ?? string.Empty,
					AdditionalInformation = error.AdditionalInformation ?? string.Empty,
				} );
			return failure;
		}

		public override async Task<OrderIF_v2_placeOrderResponse> placeOrder( OrderIF_v2_placeOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.placeOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					IOrderIF_v2.OrderDTO order;
					order = request.Order != null ? IOrderIF_v2.OrderDTO.FromGrpc( request.Order ) : null;

					// calling the service function itself
					var response = await _service.placeOrder( ctx , order );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new OrderIF_v2_placeOrderResponse() { Status = ServiceKit.Protos.Statuses.Ok };
							result.Value = response.Value != null ? IOrderIF_v2.OrderDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return _GrpcFailure_placeOrder( Statuses.NotImplemented, new [] { new ServiceKit.Net.Error() { MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF_v2.placeOrder'" } } );
						}
					}
					else
					{
						return _GrpcFailure_placeOrder( response.Status, response.Errors );
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return _GrpcFailure_placeOrder( failure.Status, failure.Errors );
				}
			}
		}

		private static OrderIF_v2_placeOrderResponse _GrpcFailure_placeOrder( Statuses status, IEnumerable<ServiceKit.Net.Error> errors )
		{
			var failure = new OrderIF_v2_placeOrderResponse() { Status = status.ToGrpc() };
			foreach( var error in errors )
				failure.Errors.Add( new ServiceKit.Protos.Error() {
					Path = error.Path ?? string.Empty,
					MessageText = error.MessageText ?? string.Empty,
					AdditionalInformation = error.AdditionalInformation ?? string.Empty,
				} );
			return failure;
		}

		public override async Task<OrderIF_v2_justOrderResponse> justOrder( OrderIF_v2_justOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v2.justOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string orderId;
					orderId = request.OrderId;

					// calling the service function itself
					var response = await _service.justOrder( ctx , orderId );

					if( response.IsSuccess() == true )
					{
						return new OrderIF_v2_justOrderResponse() { Status = ServiceKit.Protos.Statuses.Ok };
					}
					else
					{
						return _GrpcFailure_justOrder( response.Status, response.Errors );
					}
					
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return _GrpcFailure_justOrder( failure.Status, failure.Errors );
				}
			}
		}

		private static OrderIF_v2_justOrderResponse _GrpcFailure_justOrder( Statuses status, IEnumerable<ServiceKit.Net.Error> errors )
		{
			var failure = new OrderIF_v2_justOrderResponse() { Status = status.ToGrpc() };
			foreach( var error in errors )
				failure.Errors.Add( new ServiceKit.Protos.Error() {
					Path = error.Path ?? string.Empty,
					MessageText = error.MessageText ?? string.Empty,
					AdditionalInformation = error.AdditionalInformation ?? string.Empty,
				} );
			return failure;
		}
	}
}
