// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.Extensions.Logging;
using Sales.OrderManagement;
using Serilog.Context;
using ServiceKit.Net;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.Swagger;
using System.Linq;
using System.Net.Mime;

namespace Sales.OrderManagement
{
	/// The published surface of orders: DTOs only, no domain type ever reaches the wire.
	[ApiController]
	[Route( "sales/ordermanagement/orderif/v1" )]
	[SwaggerTag( "The published surface of orders: DTOs only, no domain type ever reaches the wire." )]
	public class OrderIF_v1_RestController : ControllerBase 
	{
		private readonly ILogger<OrderIF_v1_RestController> _logger;
		private readonly IOrderIF_v1 _service;
		public OrderIF_v1_RestController( ILogger<OrderIF_v1_RestController> logger, IOrderIF_v1 service )
		{
			_logger = logger; 
			_service = service; 
		}

		private static (Statuses Status, IList<ServiceKit.Net.Error> Errors) _MapFailure( Exception ex )
		{
			// a broken field is the caller's to fix, and every rule that failed is worth reporting
			if( ex is PolyPersist.Net.Common.ValidationExeption validationExeption )
				return (Statuses.BadRequest, validationExeption.ValidationErrors.Select( validationError => new ServiceKit.Net.Error() {
					Path = validationError.Path,
					MessageText = validationError.ErrorText,
					AdditionalInformation = $"{validationError.TypeOfEntity}.{validationError.MemberOfEntity}",
				} ).ToList<ServiceKit.Net.Error>());

			if( ex is PolyPersist.Net.Common.NotFoundException )
				return (Statuses.NotFound, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			if( ex is PolyPersist.Net.Common.DuplicateKeyException
				|| ex is PolyPersist.Net.Common.ConcurrencyConflictException
				|| ex is PolyPersist.Net.Common.InvalidRequestException )
				return (Statuses.BadRequest, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message } });

			// anything else really is ours: the caller can do nothing about it, so say so plainly
			return (Statuses.InternalError, new List<ServiceKit.Net.Error>() { new() { MessageText = ex.Message, AdditionalInformation = ex.ToString() } });
		}

		[HttpGet( "getorder/{orderId}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(IOrderIF_v1.OrderDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> getOrder( [FromRoute] string orderId)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.getOrder" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.getOrder( ctx, orderId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(Statuses.NotImplemented.ToHttp(), new List<ServiceKit.Net.Error>() { new() { MessageText = "Not handled reponse in REST Controller when calling 'OrderIF_v1.getOrder'" } } );
						}
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}

		[HttpPost( "placeorder" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(IOrderIF_v1.OrderDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> placeOrder( [FromBody] IOrderIF_v1.OrderDTO order)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.placeOrder" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.placeOrder( ctx, order );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(Statuses.NotImplemented.ToHttp(), new List<ServiceKit.Net.Error>() { new() { MessageText = "Not handled reponse in REST Controller when calling 'OrderIF_v1.placeOrder'" } } );
						}
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}

		[HttpPost( "setprice" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "", typeof(IOrderIF_v1.OrderItemDTO) )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> setPrice( [FromBody] IOrderIF_v1.OrderItemDTO orderItem,  [FromQuery] decimal price)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.setPrice" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.setPrice( ctx, orderItem, price );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							return Ok(response.Value);
						}
						else
						{
							return StatusCode(Statuses.NotImplemented.ToHttp(), new List<ServiceKit.Net.Error>() { new() { MessageText = "Not handled reponse in REST Controller when calling 'OrderIF_v1.setPrice'" } } );
						}
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}

		[HttpPost( "justorder/{orderId}" )] 
		[Produces( MediaTypeNames.Application.Json )]
		[SwaggerResponse( StatusCodes.Status200OK, "Ok" )]
		[SwaggerResponse( StatusCodes.Status400BadRequest, nameof(StatusCodes.Status400BadRequest), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status408RequestTimeout, nameof(StatusCodes.Status408RequestTimeout), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status404NotFound, nameof(StatusCodes.Status404NotFound), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status401Unauthorized, nameof(StatusCodes.Status401Unauthorized), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status501NotImplemented, nameof(StatusCodes.Status501NotImplemented), typeof(IList<ServiceKit.Net.Error>) )]
		[SwaggerResponse( StatusCodes.Status500InternalServerError, nameof(StatusCodes.Status500InternalServerError), typeof(IList<ServiceKit.Net.Error>) )]
		public async Task<IActionResult> justOrder( [FromRoute] string orderId)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.justOrder" ))
			{
				CallingContext ctx = CallingContext.FromHttpContext( HttpContext, _logger );
				try
				{
					// calling the service function itself
					var response = await _service.justOrder( ctx, orderId );

					if( response.IsSuccess() == true )
					{
						return Ok();
					}
					else
					{
						return StatusCode(response.Status.ToHttp(), response.Errors);
					}
				}
				catch(Exception ex)
				{
					var failure = _MapFailure( ex );
					return StatusCode(failure.Status.ToHttp(), failure.Errors);
				}
			}
		}
	}
}
