// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using Google.Protobuf.WellKnownTypes;
using Grpc.Core;
using Microsoft.Extensions.Logging;
using Sales.OrderManagement;
using Sales.OrderManagement.Protos.OrderIF_v1;
using Serilog.Context;
using ServiceKit.Net;
using System.Globalization;

namespace Sales.OrderManagement
{
	/// The published surface of orders: DTOs only, no domain type ever reaches the wire.
	public class OrderIF_v1_GrpcController : Sales.OrderManagement.Protos.OrderIF_v1.OrderIF_v1.OrderIF_v1Base 
	{
		private readonly ILogger<OrderIF_v1_GrpcController> _logger;
		private readonly IOrderIF_v1 _service;

		public OrderIF_v1_GrpcController( ILogger<OrderIF_v1_GrpcController> logger, IOrderIF_v1 service )
		{
			_logger = logger; 
			_service = service; 
		}

		public override async Task<OrderIF_v1_getOrderResponse> getOrder( OrderIF_v1_getOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.getOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string orderId;
					orderId = request.OrderId;

					// calling the service function itself
					var response = await _service.getOrder( ctx , orderId );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new OrderIF_v1_getOrderResponse();
							result.Value = response.Value != null ? IOrderIF_v1.OrderDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return new OrderIF_v1_getOrderResponse {
								Error = new () {
									Status = ServiceKit.Protos.Statuses.NotImplemented,
									MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF_v1.getOrder'",
								}
							};
						}
					}
					else
					{
						return new OrderIF_v1_getOrderResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_getOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
			}
		}

		public override async Task<OrderIF_v1_placeOrderResponse> placeOrder( OrderIF_v1_placeOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.placeOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					IOrderIF_v1.OrderDTO order;
					order = request.Order != null ? IOrderIF_v1.OrderDTO.FromGrpc( request.Order ) : null;

					// calling the service function itself
					var response = await _service.placeOrder( ctx , order );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new OrderIF_v1_placeOrderResponse();
							result.Value = response.Value != null ? IOrderIF_v1.OrderDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return new OrderIF_v1_placeOrderResponse {
								Error = new () {
									Status = ServiceKit.Protos.Statuses.NotImplemented,
									MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF_v1.placeOrder'",
								}
							};
						}
					}
					else
					{
						return new OrderIF_v1_placeOrderResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_placeOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
			}
		}

		public override async Task<OrderIF_v1_setPriceResponse> setPrice( OrderIF_v1_setPriceRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.setPrice" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					IOrderIF_v1.OrderItemDTO orderItem;
					orderItem = request.OrderItem != null ? IOrderIF_v1.OrderItemDTO.FromGrpc( request.OrderItem ) : null;
					decimal price;
					price = decimal.Parse(request.Price, CultureInfo.InvariantCulture);

					// calling the service function itself
					var response = await _service.setPrice( ctx , orderItem, price );

					if( response.IsSuccess() == true )
					{
						if( response.HasValue() == true )
						{
							var result = new OrderIF_v1_setPriceResponse();
							result.Value = response.Value != null ? IOrderIF_v1.OrderItemDTO.ToGrpc( response.Value ) : null;
							return result;
						}
						else
						{
							return new OrderIF_v1_setPriceResponse {
								Error = new () {
									Status = ServiceKit.Protos.Statuses.NotImplemented,
									MessageText = "Not handled reponse in GRPC Controller when calling 'OrderIF_v1.setPrice'",
								}
							};
						}
					}
					else
					{
						return new OrderIF_v1_setPriceResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_setPriceResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
			}
		}

		public override async Task<OrderIF_v1_justOrderResponse> justOrder( OrderIF_v1_justOrderRequest request, ServerCallContext grpcContext)
		{
			using(LogContext.PushProperty( "Scope", "OrderIF_v1.justOrder" ))
			{
				CallingContext ctx = CallingContext.FromGrpcContext( grpcContext, _logger );
				try
				{
					string orderId;
					orderId = request.OrderId;

					// calling the service function itself
					var response = await _service.justOrder( ctx , orderId );

					if( response.IsSuccess() == true )
					{
						return new OrderIF_v1_justOrderResponse {
							Success = new Empty()
						};
					}
					else
					{
						return new OrderIF_v1_justOrderResponse {
							Error = new () {
								Status = response.Error.Status.ToGrpc(),
								MessageText = response.Error.MessageText,
								AdditionalInformation = response.Error.AdditionalInformation
							}
						};
					}
					
				}
				catch(Exception ex)
				{
					return new OrderIF_v1_justOrderResponse {
						Error = new () {
							Status = ServiceKit.Protos.Statuses.InternalError,
							MessageText = ex.Message,
							AdditionalInformation = ex.ToString()
						}
					};
				}
			}
		}
	}
}
