// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;

namespace CustomerManagement.Customers.Customer
{
	public enum CustomerStatuses
	{
		/// Registered but the e-mail address has not been confirmed yet
		Pending,

		/// Ordinary, active customer
		Active,

		/// Temporarily barred from ordering
		Suspended,

		/// Left, kept only for the orders already placed
		Closed,

	}
}
