// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using CustomerManagement.Customers;
using PolyPersist;
using PolyPersist.Net.Common;
using System.Text.RegularExpressions;

namespace CustomerManagement.Customers.Customer
{
	public partial class CustomerAccount : Core.Base.IBaseEntity, IEquatable<CustomerAccount>, IValidable
	{
		#region IBaseEntity
		public string id { get; set; }
		public string etag { get; set; }
		public DateTime LastUpdate { get; set; }
		#endregion IBaseEntity

		public string name { get; set; }
		public string email { get; set; }
		public string? phone { get; set; }
		public CustomerStatuses status { get; set; }
		/// Optional, and that is a business statement rather than a convenience: at
		/// registration there is a name and an e-mail address and nothing else - the billing
		/// address arrives with the first order. Declaring it mandatory made a customer that
		/// could not be registered at all, because the only way to satisfy the rule was to
		/// invent an empty address that then broke every rule PostalAddress has.
		public PostalAddress? billingAddress { get; set; }
		public PostalAddress? shippingAddress { get; set; }

		#region Clone 
		public virtual CustomerAccount Clone()
		{
			CustomerAccount clone = new();

			// begin: BaseEntity
			// end: BaseEntity

			clone.name = new string(name.ToCharArray());
			clone.email = new string(email.ToCharArray());
			clone.phone = new string(phone.ToCharArray());
			clone.status = status;

			// clone of billingAddress
			clone.billingAddress = billingAddress?.Clone();

			// clone of shippingAddress
			clone.shippingAddress = shippingAddress?.Clone();

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( CustomerAccount other )
		{
			if (other is null) return false;

			// begin: BaseEntity
			// end: BaseEntity

			if(name != other.name) return false;
			if(email != other.email) return false;
			if(phone != other.phone) return false;
			if(status != other.status) return false;

			// equals of billingAddress
			if(billingAddress == null && other.billingAddress != null ) return false;
			if(billingAddress != null && billingAddress.Equals(other.billingAddress) == false ) return false;

			// equals of shippingAddress
			if(shippingAddress == null && other.shippingAddress != null ) return false;
			if(shippingAddress != null && shippingAddress.Equals(other.shippingAddress) == false ) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as CustomerAccount);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			// begin: BaseEntity
			// end: BaseEntity

			hash.Add(name);
			hash.Add(email);
			hash.Add(phone);
			hash.Add(status);

			// hash of billingAddress
			if(billingAddress != null ) hash.Add(billingAddress);

			// hash of shippingAddress
			if(shippingAddress != null ) hash.Add(shippingAddress);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 

		#region Validation
		public virtual bool Validate( IList<IValidationError> errors )
		{
			int before = errors.Count;
			ValidateInto( errors, string.Empty );
			return errors.Count == before;
		}

		public virtual void ValidateInto( IList<IValidationError> errors, string pathPrefix )
		{
			if ((name?.Length ?? 0) <= 1)
				errors.Add( new ValidationError { TypeOfEntity = "CustomerAccount", MemberOfEntity = "name", Path = pathPrefix + "name", ErrorText = "name must satisfy: len(name) > 1" } );

			if (!Regex.IsMatch(email ?? string.Empty, "[^@ ]+@[^@ ]+\\.[^@ ]+"))
				errors.Add( new ValidationError { TypeOfEntity = "CustomerAccount", MemberOfEntity = "email", Path = pathPrefix + "email", ErrorText = "email must satisfy: matches(email, \"[^@ ]+@[^@ ]+\\\\.[^@ ]+\")" } );

			billingAddress?.ValidateInto( errors, pathPrefix + "billingAddress." );

			shippingAddress?.ValidateInto( errors, pathPrefix + "shippingAddress." );
		}
		#endregion Validation
	}

}
