// <auto-generated>
//     This code was generated by d3i.interpreter
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
using System;
using System.Collections.Generic;
using PolyPersist;
using PolyPersist.Net.Common;

namespace CustomerManagement.Customers.Customer
{
	/// A postal address is a value: two addresses with the same fields are the same address,
	/// so it has no identity of its own and is embedded rather than referenced.
	public partial class PostalAddress : IEquatable<PostalAddress>, IValidable
	{
		public string country { get; set; }
		public string postalCode { get; set; }
		public string city { get; set; }
		public string street { get; set; }

		#region Clone 
		public virtual PostalAddress Clone()
		{
			PostalAddress clone = new();

			clone.country = new string(country.ToCharArray());
			clone.postalCode = new string(postalCode.ToCharArray());
			clone.city = new string(city.ToCharArray());
			clone.street = new string(street.ToCharArray());

			return clone;
		}
		#endregion Clone 

		#region Equals & HashCode 
		public bool Equals( PostalAddress other )
		{
			if (other is null) return false;

			if(country != other.country) return false;
			if(postalCode != other.postalCode) return false;
			if(city != other.city) return false;
			if(street != other.street) return false;

			return true;
		}

		public override bool Equals(object obj) => Equals(obj as PostalAddress);

		public override int GetHashCode()
		{
			var hash = new HashCode();
			hash.Add(country);
			hash.Add(postalCode);
			hash.Add(city);
			hash.Add(street);

			return hash.ToHashCode();
		}
		#endregion Equals & HashCode 

		#region Validation
		public virtual bool Validate( IList<IValidationError> errors )
		{
			int before = errors.Count;
			ValidateInto( errors, string.Empty );
			return errors.Count == before;
		}

		public virtual void ValidateInto( IList<IValidationError> errors, string pathPrefix )
		{
			if ((country?.Length ?? 0) != 2)
				errors.Add( new ValidationError { TypeOfEntity = "PostalAddress", MemberOfEntity = "country", Path = pathPrefix + "country", ErrorText = "country must satisfy: len(value) == 2" } );

			if ((postalCode?.Length ?? 0) <= 0)
				errors.Add( new ValidationError { TypeOfEntity = "PostalAddress", MemberOfEntity = "postalCode", Path = pathPrefix + "postalCode", ErrorText = "postalCode must satisfy: len(value) > 0" } );

			if ((city?.Length ?? 0) <= 0)
				errors.Add( new ValidationError { TypeOfEntity = "PostalAddress", MemberOfEntity = "city", Path = pathPrefix + "city", ErrorText = "city must satisfy: len(value) > 0" } );

			if ((street?.Length ?? 0) <= 0)
				errors.Add( new ValidationError { TypeOfEntity = "PostalAddress", MemberOfEntity = "street", Path = pathPrefix + "street", ErrorText = "street must satisfy: len(value) > 0" } );
		}
		#endregion Validation
	}

}
